#!/usr/bin/env python3
"""
add_missing_stocks.py
Add 400+ missing NSE/BSE stocks to nse_stock_taxonomy.csv
Covers: Nifty500, Midcap150, SmallCap250, recent IPOs (2023-2026)
"""
import csv
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parents[1]
CSV  = ROOT / "data" / "nse_stock_taxonomy.csv"

# Load existing
fieldnames = ["nse_ticker", "sector", "industry", "notes"]
existing = {}
with open(CSV, newline="", encoding="utf-8") as f:
    for row in csv.DictReader(f):
        t = row.get("nse_ticker", "").strip().upper()
        if t:
            existing[t] = row

NEW_STOCKS = [
    # ── NIFTY50 / NIFTY100 ADDITIONS ────────────────────────────────────────
    ("HDFCBANK",    "Banking",    "Private Banks"),
    ("ICICIBANK",   "Banking",    "Private Banks"),
    ("KOTAKBANK",   "Banking",    "Private Banks"),
    ("AXISBANK",    "Banking",    "Private Banks"),
    ("INDUSINDBK",  "Banking",    "Private Banks"),
    ("FEDERALBNK",  "Banking",    "Private Banks"),
    ("IDFCFIRSTB",  "Banking",    "Private Banks"),
    ("BANDHANBNK",  "Banking",    "Small Finance Banks"),
    ("AUBANK",      "Banking",    "Small Finance Banks"),
    ("EQUITASBNK",  "Banking",    "Small Finance Banks"),
    ("SBIN",        "Banking",    "PSU Banks"),
    ("PNB",         "Banking",    "PSU Banks"),
    ("BANKBARODA",  "Banking",    "PSU Banks"),
    ("CANBK",       "Banking",    "PSU Banks"),
    ("UNIONBANK",   "Banking",    "PSU Banks"),
    ("IDBI",        "Banking",    "PSU Banks"),

    # ── FINANCIALS ───────────────────────────────────────────────────────────
    ("BAJFINANCE",  "Financials", "Consumer Finance"),
    ("BAJAJFINSV",  "Financials", "Insurance & Finance"),
    ("CHOLAFIN",    "Financials", "Vehicle Finance"),
    ("MUTHOOTFIN",  "Financials", "Gold Loans"),
    ("MANAPPURAM",  "Financials", "Gold Loans"),
    ("LICHSGFIN",   "Financials", "Housing Finance"),
    ("CANFINHOME",  "Financials", "Housing Finance"),
    ("HDFCLIFE",    "Financials", "Life Insurance"),
    ("SBILIFE",     "Financials", "Life Insurance"),
    ("ICICIPRU",    "Financials", "Life Insurance"),
    ("LICI",        "Financials", "Life Insurance"),
    ("NIACL",       "Financials", "Non-Life Insurance"),
    ("STARHEALTH",  "Financials", "Health Insurance"),
    ("GICRE",       "Financials", "Reinsurance"),
    ("POLICYBZR",   "Financials", "Fintech & Insurtech"),
    ("PAYTM",       "Financials", "Fintech & Insurtech"),
    ("FINCABLES",   "Financials", "NBFC"),
    ("IIFL",        "Financials", "NBFC"),
    ("SUNDARMFIN",  "Financials", "Vehicle Finance"),
    ("M&MFIN",      "Financials", "Vehicle Finance"),
    ("SHRIRAMFIN",  "Financials", "Vehicle Finance"),
    ("CREDITACC",   "Financials", "Microfinance"),
    ("SPANDANA",    "Financials", "Microfinance"),
    ("FUSION",      "Financials", "Microfinance"),
    ("BSE",         "Financials", "Capital Markets"),
    ("MCX",         "Financials", "Capital Markets"),
    ("CDSL",        "Financials", "Capital Markets"),
    ("CAMS",        "Financials", "Capital Markets"),
    ("KFINTECH",    "Financials", "Capital Markets"),
    ("NSDL",        "Financials", "Capital Markets"),
    ("HDFCAMC",     "Financials", "Wealth Management"),
    ("NIPPONAMC",   "Financials", "Wealth Management"),
    ("ABSLAMC",     "Financials", "Wealth Management"),
    ("UTIAMC",      "Financials", "Wealth Management"),
    ("ANGELONE",    "Financials", "Broking"),
    ("ICICISEC",    "Financials", "Broking"),
    ("5PAISA",      "Financials", "Broking"),
    ("MOFSL",       "Financials", "Wealth Management"),
    ("NUVAMA",      "Financials", "Wealth Management"),
    ("ANANDRATHI",  "Financials", "Wealth Management"),
    ("SAMMAANCAP",  "Financials", "Wealth Management"),
    ("360ONE",      "Financials", "Wealth Management"),
    ("DSPIM",       "Financials", "Wealth Management"),
    ("PRUDENT",     "Financials", "Wealth Management"),

    # ── IT ───────────────────────────────────────────────────────────────────
    ("TCS",         "IT", "IT Services"),
    ("INFY",        "IT", "IT Services"),
    ("WIPRO",       "IT", "IT Services"),
    ("HCLTECH",     "IT", "IT Services"),
    ("TECHM",       "IT", "IT Services"),
    ("LTI",         "IT", "IT Services"),
    ("LTIM",        "IT", "IT Services"),
    ("MPHASIS",     "IT", "IT Services"),
    ("PERSISTENT",  "IT", "IT Services"),
    ("COFORGE",     "IT", "IT Services"),
    ("KPITTECH",    "IT", "IT Automotive"),
    ("MASTEK",      "IT", "IT Services"),
    ("ZENSAR",      "IT", "IT Services"),
    ("HEXAWARE",    "IT", "IT Services"),
    ("BIRLASOFT",   "IT", "IT Services"),
    ("NIIT",        "IT", "IT Services"),
    ("NIITNX",      "IT", "IT Services"),
    ("FSS",         "IT", "Fintech Software"),
    ("ZENSARTECH",  "IT", "IT Services"),
    ("INTELLECT",   "IT", "Fintech Software"),
    ("ECLERX",      "IT", "BPO & KPO"),
    ("MFSL",        "IT", "IT Services"),
    ("OFSS",        "IT", "IT Services"),
    ("SASKEN",      "IT", "IT Embedded"),
    ("RATEGAIN",    "IT", "SaaS"),
    ("INDIAMART",   "Internet", "B2B Marketplace"),
    ("JUSTDIAL",    "Internet", "Local Search"),
    ("MAPMYINDIA",  "IT", "Geospatial & Maps"),
    ("TATAELXSI",   "IT", "Engineering Services"),
    ("LATENTVIEW",  "IT", "Data Analytics"),
    ("XCHANGING",   "IT", "IT Services"),

    # ── CONSUMER INTERNET ────────────────────────────────────────────────────
    ("NYKAA",       "Internet", "Beauty E-Commerce"),
    ("ZOMATO",      "Internet", "Food Delivery"),
    ("SWIGGY",      "Internet", "Food Delivery"),
    ("DMART",       "Consumer", "Retail Supermarkets"),
    ("TRENT",       "Consumer", "Retail Fashion"),
    ("SHOPERSTOP",  "Consumer", "Retail Fashion"),
    ("VMART",       "Consumer", "Value Retail"),
    ("BATAINDIA",   "Consumer", "Footwear"),
    ("METROBRAND",  "Consumer", "Footwear"),
    ("CAMPUS",      "Consumer", "Footwear"),
    ("RELAXO",      "Consumer", "Footwear"),
    ("MANYAVAR",    "Consumer", "Ethnic Fashion"),
    ("VEDANT",      "Consumer", "Ethnic Fashion"),
    ("PAGEIND",     "Consumer", "Innerwear & Hosiery"),
    ("DOLLAR",      "Consumer", "Innerwear & Hosiery"),
    ("LOVABLE",     "Consumer", "Innerwear & Hosiery"),

    # ── FMCG ─────────────────────────────────────────────────────────────────
    ("HINDUNILVR",  "FMCG", "FMCG - HPC"),
    ("ITC",         "FMCG", "FMCG - Tobacco"),
    ("NESTLEIND",   "FMCG", "FMCG - Foods"),
    ("BRITANNIA",   "FMCG", "FMCG - Foods"),
    ("DABUR",       "FMCG", "FMCG - HPC"),
    ("MARICO",      "FMCG", "FMCG - HPC"),
    ("GODREJCP",    "FMCG", "FMCG - HPC"),
    ("PGHH",        "FMCG", "FMCG - HPC"),
    ("COLPAL",      "FMCG", "FMCG - HPC"),
    ("EMAMILTD",    "FMCG", "FMCG - HPC"),
    ("BAJAJCON",    "FMCG", "FMCG - HPC"),
    ("ZYDUSWELL",   "FMCG", "FMCG - HPC"),
    ("VBL",         "FMCG", "FMCG - Beverages"),
    ("CCL",         "FMCG", "FMCG - Beverages"),
    ("RADICO",      "FMCG", "FMCG - Spirits"),
    ("MCDOWELL-N",  "FMCG", "FMCG - Spirits"),
    ("UBL",         "FMCG", "FMCG - Beverages"),
    ("TATACONSUM",  "FMCG", "FMCG - Foods"),
    ("PATANJALI",   "FMCG", "FMCG - HPC"),
    ("JYOTHYLAB",   "FMCG", "FMCG - HPC"),
    ("BIKAJI",      "FMCG", "FMCG - Snacks"),
    ("PRATAAP",     "FMCG", "FMCG - Snacks"),
    ("DFM",         "FMCG", "FMCG - Snacks"),
    ("HATSUN",      "FMCG", "FMCG - Dairy"),
    ("PARAG",       "FMCG", "FMCG - Dairy"),
    ("PRABHAT",     "FMCG", "FMCG - Dairy"),
    ("DODLA",       "FMCG", "FMCG - Dairy"),
    ("AAVIN",       "FMCG", "FMCG - Dairy"),
    ("CELLO",       "Consumer", "Plastics & Furniture"),
    ("TUPPERWARE",  "Consumer", "Plastics & Furniture"),

    # ── PHARMA ───────────────────────────────────────────────────────────────
    ("SUNPHARMA",   "Pharma", "Formulations"),
    ("DRREDDY",     "Pharma", "Formulations"),
    ("CIPLA",       "Pharma", "Formulations"),
    ("LUPIN",       "Pharma", "Formulations"),
    ("DIVISLAB",    "Pharma", "API & Bulk Drugs"),
    ("AUROPHARMA",  "Pharma", "Formulations"),
    ("ALEMBICPHARM","Pharma", "Formulations"),
    ("AJANTPHARM",  "Pharma", "Formulations"),
    ("IPCALAB",     "Pharma", "Formulations"),
    ("GLAND",       "Pharma", "Injectables"),
    ("STRIDES",     "Pharma", "Formulations"),
    ("BLISSGVS",    "Pharma", "Formulations"),
    ("LAURUS",      "Pharma", "API & Bulk Drugs"),
    ("SOLARA",      "Pharma", "API & Bulk Drugs"),
    ("SUVEN",       "Pharma", "API & Bulk Drugs"),
    ("DRREDDYS",    "Pharma", "Formulations"),
    ("TORNTPHRM",   "Pharma", "Formulations"),
    ("BIOCON",      "Pharma", "Biosimilars"),
    ("ZYDUSLIFE",   "Pharma", "Formulations"),
    ("ABBOTINDIA",  "Pharma", "MNC Pharma"),
    ("SANOFI",      "Pharma", "MNC Pharma"),
    ("PFIZER",      "Pharma", "MNC Pharma"),
    ("GLAXO",       "Pharma", "MNC Pharma"),
    ("ASTRAZEN",    "Pharma", "MNC Pharma"),
    ("METROPOLIS",  "Pharma", "Diagnostics"),
    ("DRLALPATH",   "Pharma", "Diagnostics"),
    ("THYROCARE",   "Pharma", "Diagnostics"),
    ("KRSNAA",      "Pharma", "Diagnostics"),
    ("SUVRDP",      "Pharma", "Diagnostics"),
    ("VIJAYA",      "Pharma", "Diagnostics"),
    ("APOLLOHOSP",  "Pharma", "Hospitals"),
    ("FORTIS",      "Pharma", "Hospitals"),
    ("ASTERDM",     "Pharma", "Hospitals"),
    ("NARAYANA",    "Pharma", "Hospitals"),
    ("MAXHEALTH",   "Pharma", "Hospitals"),
    ("YATHARTH",    "Pharma", "Hospitals"),
    ("RAINBOW",     "Pharma", "Hospitals"),
    ("MEDANTA",     "Pharma", "Hospitals"),
    ("KIMS",        "Pharma", "Hospitals"),
    ("NHLIND",      "Pharma", "Hospitals"),
    ("SHILPAMED",   "Pharma", "Med Devices"),
    ("POLYMED",     "Pharma", "Med Devices"),
    ("HLEGLAS",     "Pharma", "Pharma Packaging"),
    ("IOLCP",       "Pharma", "API & Bulk Drugs"),
    ("AKUMS",       "Pharma", "CDMO"),
    ("DIVI",        "Pharma", "API & Bulk Drugs"),

    # ── AUTO ─────────────────────────────────────────────────────────────────
    ("MARUTI",      "Auto", "Auto OEM - 4W"),
    ("TATAMOTORS",  "Auto", "Auto OEM - 4W"),
    ("M&M",         "Auto", "Auto OEM - 4W"),
    ("HEROMOTOCO",  "Auto", "Auto OEM - 2W"),
    ("BAJAJ-AUTO",  "Auto", "Auto OEM - 2W"),
    ("TVSMOTORS",   "Auto", "Auto OEM - 2W"),
    ("EICHERMOT",   "Auto", "Auto OEM - 2W"),
    ("ROYALENF",    "Auto", "Auto OEM - 2W"),
    ("OLECTRA",     "Auto", "Auto OEM - EV"),
    ("TATAMOTR",    "Auto", "Auto OEM - EV"),
    ("MOTHERSON",   "Auto", "Auto Ancillaries"),
    ("MINDA",       "Auto", "Auto Ancillaries"),
    ("MINDAIND",    "Auto", "Auto Ancillaries"),
    ("ENDURANCE",   "Auto", "Auto Ancillaries"),
    ("CRAFTSMAN",   "Auto", "Auto Ancillaries"),
    ("SANSERA",     "Auto", "Metal Forgings & Castings"),
    ("BHARATFORG",  "Auto", "Metal Forgings & Castings"),
    ("GNA",         "Auto", "Metal Forgings & Castings"),
    ("NELCAST",     "Auto", "Metal Forgings & Castings"),
    ("MAHINDCIE",   "Auto", "Metal Forgings & Castings"),
    ("SHREERENUKA", "Sugar", "Sugar"),
    ("EXIDEIND",    "Auto", "Batteries"),
    ("AMARON",      "Auto", "Batteries"),
    ("GRAVITA",     "Metals", "Lead Recycling"),
    ("PRICOL",      "Auto", "Auto Ancillaries"),
    ("SUBROS",      "Auto", "Auto Ancillaries"),
    ("SUPRAJIT",    "Auto", "Auto Ancillaries"),
    ("AUTOEQ",      "Auto", "Auto Ancillaries"),
    ("SAREGAMA",    "Consumer", "Media & Entertainment"),

    # ── METALS ───────────────────────────────────────────────────────────────
    ("TATASTEEL",   "Metals", "Steel"),
    ("JSWSTEEL",    "Metals", "Steel"),
    ("SAIL",        "Metals", "Steel"),
    ("JINDALSTEL",  "Metals", "Steel"),
    ("JINDALSAW",   "Metals", "Steel Pipes"),
    ("APLAPOLLO",   "Metals", "Steel Pipes"),
    ("RATNAMANI",   "Metals", "Steel Pipes"),
    ("WELCORP",     "Metals", "Steel Pipes"),
    ("HINDALCO",    "Metals", "Aluminium"),
    ("NALCO",       "Metals", "Aluminium"),
    ("HINDZINC",    "Metals", "Zinc & Lead"),
    ("VEDL",        "Metals", "Diversified Metals"),
    ("NMDC",        "Metals", "Iron Ore"),
    ("MOIL",        "Metals", "Manganese"),
    ("GPIL",        "Metals", "Steel"),
    ("GRAPHITE",    "Metals", "Graphite Electrodes"),
    ("HEG",         "Metals", "Graphite Electrodes"),
    ("NIFTYMET",    "Metals", "Steel"),
    ("TATAMET",     "Metals", "Steel"),
    ("TIINDIA",     "Metals", "Specialty Metals"),
    ("MIDHANI",     "Defense", "Aerospace Alloys"),
    ("MSTCLTD",     "Metals", "E-Commerce Metals"),
    ("IFGL",        "Metals", "Refractories"),
    ("OCCL",        "Metals", "Refractories"),
    ("KALYANKJIL",  "Consumer", "Jewellery"),
    ("TITANBYK",    "Consumer", "Watches & Jewellery"),
    ("TITAN",       "Consumer", "Watches & Jewellery"),
    ("PCJEWELLER",  "Consumer", "Jewellery"),
    ("SENCO",       "Consumer", "Jewellery"),
    ("GOLDIAM",     "Consumer", "Jewellery"),
    ("GOLDBEES",    "Metals", "Gold ETF"),

    # ── ENERGY & OIL ─────────────────────────────────────────────────────────
    ("RELIANCE",    "Energy", "Oil & Gas Integrated"),
    ("ONGC",        "Energy", "Oil & Gas E&P"),
    ("OIL",         "Energy", "Oil & Gas E&P"),
    ("IOC",         "Energy", "Oil Refining"),
    ("BPCL",        "Energy", "Oil Refining"),
    ("HPCL",        "Energy", "Oil Refining"),
    ("MRPL",        "Energy", "Oil Refining"),
    ("CHENNPETRO",  "Energy", "Oil Refining"),
    ("GAIL",        "Energy", "Gas Distribution"),
    ("PETRONET",    "Energy", "LNG Terminal"),
    ("IGL",         "Energy", "City Gas Distribution"),
    ("MGL",         "Energy", "City Gas Distribution"),
    ("GSPL",        "Energy", "Gas Distribution"),
    ("GUJGASLTD",   "Energy", "City Gas Distribution"),
    ("AEGASIND",    "Energy", "City Gas Distribution"),
    ("NTPC",        "Energy", "Power Generation"),
    ("POWERGRID",   "Energy", "Power Transmission"),
    ("NHPC",        "Energy", "Hydro Power"),
    ("SJVN",        "Energy", "Hydro Power"),
    ("TATAPOWER",   "Energy", "Power Integrated"),
    ("CESC",        "Energy", "Power Integrated"),
    ("TORNTPOWER",  "Energy", "Power Integrated"),
    ("JSWENERGY",   "Renewable", "Power Integrated"),
    ("COALINDIA",   "Energy", "Coal Mining"),
    ("MOIL",        "Metals", "Manganese"),

    # ── RENEWABLE ENERGY ─────────────────────────────────────────────────────
    ("ADANIGREEN",  "Renewable", "Solar Power"),
    ("ADANIENSOL",  "Renewable", "Solar Power"),
    ("ACMESOLAR",   "Renewable", "Solar Power"),
    ("WAAREEENER",  "Renewable", "Solar Modules"),
    ("PREMIERENRG", "Renewable", "Solar Modules"),
    ("GOLDENKA",    "Renewable", "Solar Modules"),
    ("WEBSOL",      "Renewable", "Solar Cells"),
    ("SUZLON",      "Renewable", "Wind Energy"),
    ("INOXWIND",    "Renewable", "Wind Energy"),
    ("WINDWORLD",   "Renewable", "Wind Energy"),
    ("GREENKO",     "Renewable", "Hydro Power"),
    ("GREENPOWER",  "Renewable", "Power Integrated"),

    # ── INFRASTRUCTURE ───────────────────────────────────────────────────────
    ("LT",          "Cap Goods", "EPC & Engineering"),
    ("LARSEN",      "Cap Goods", "EPC & Engineering"),
    ("KECINTL",     "Cap Goods", "Power T&D"),
    ("KALPATPOWR",  "Cap Goods", "Power T&D"),
    ("KEC",         "Cap Goods", "Power T&D"),
    ("JYOTICNC",    "Cap Goods", "Machine Tools"),
    ("GRINDWELL",   "Cap Goods", "Abrasives"),
    ("CUMI",        "Cap Goods", "Abrasives"),
    ("THERMAX",     "Cap Goods", "Heat Exchange & Energy"),
    ("ELGI",        "Cap Goods", "Air Compressors"),
    ("KNRCON",      "Infra", "Road EPC"),
    ("ASHOKA",      "Infra", "Road EPC"),
    ("HG INFRA",    "Infra", "Road EPC"),
    ("HGINFRA",     "Infra", "Road EPC"),
    ("IRB",         "Infra", "Toll Roads"),
    ("RVNL",        "Infra", "Railway EPC"),
    ("IRCON",       "Infra", "Railway EPC"),
    ("IRFC",        "Infra", "Railway Financing"),
    ("RITES",       "Infra", "Railway Consulting"),
    ("NBCC",        "Infra", "Govt Construction"),
    ("PSPPROJECT",  "Infra", "EPC"),
    ("NCC",         "Infra", "Construction EPC"),
    ("TITAGARH",    "Cap Goods", "Railway Wagons"),
    ("TEXRAIL",     "Cap Goods", "Railway Wagons"),
    ("GPT",         "Cap Goods", "Railway Sleepers"),
    ("SKIL",        "Infra", "Port & Infra"),
    ("ADANIPORTS",  "Infra", "Ports"),
    ("ESABINDIA",   "Cap Goods", "Welding Equipment"),
    ("ISGEC",       "Cap Goods", "Industrial Machinery"),
    ("BHELPSG",     "Cap Goods", "Power Equipment"),
    ("TRIVENIGR",   "Cap Goods", "Turbines"),
    ("UNIPARTS",    "Auto", "Auto Ancillaries"),
    ("CRAFTSMAN",   "Auto", "Auto Ancillaries"),

    # ── DEFENSE ──────────────────────────────────────────────────────────────
    ("HAL",         "Defense", "Aerospace & Defense"),
    ("BEL",         "Defense", "Defense Electronics"),
    ("GRSE",        "Defense", "Shipbuilding"),
    ("COCHINSHIP",  "Defense", "Shipbuilding"),
    ("MAZDOCK",     "Defense", "Shipbuilding"),
    ("DRONEACHARYA","Defense", "Drones"),
    ("ZEN",         "Defense", "Defense Electronics"),
    ("BDSL",        "Defense", "Aerospace & Defense"),
    ("ASTRA",       "Defense", "Aerospace & Defense"),
    ("PARAS",       "Defense", "Defense Electronics"),
    ("DYNAMATECH",  "Defense", "Aerospace & Defense"),
    ("GOCLCORP",    "Defense", "Explosives"),
    ("NAGAFERT",    "Chemicals", "Specialty Chemicals"),

    # ── REAL ESTATE ──────────────────────────────────────────────────────────
    ("DLF",         "RealEstate", "Residential RE"),
    ("GODREJPROP",  "RealEstate", "Residential RE"),
    ("OBEROIRLTY",  "RealEstate", "Residential RE"),
    ("PRESTIGE",    "RealEstate", "Residential RE"),
    ("MACROTECH",   "RealEstate", "Residential RE"),
    ("SOBHA",       "RealEstate", "Residential RE"),
    ("BRIGADE",     "RealEstate", "Residential RE"),
    ("MAHLIFE",     "RealEstate", "Residential RE"),
    ("KOLTEPATIL",  "RealEstate", "Residential RE"),
    ("ANANTRAJ",    "RealEstate", "Commercial RE"),
    ("SUNTECKREAL", "RealEstate", "Residential RE"),
    ("PHOENIXLTD",  "RealEstate", "Retail RE"),
    ("IBREALEST",   "RealEstate", "Commercial RE"),
    ("OMAXE",       "RealEstate", "Residential RE"),
    ("ARVSMART",    "RealEstate", "Residential RE"),
    ("SIGNATURE",   "RealEstate", "Residential RE"),
    ("KEYSTONE",    "RealEstate", "Residential RE"),
    ("PURAVANKARA", "RealEstate", "Residential RE"),
    ("ELDECO",      "RealEstate", "Residential RE"),

    # ── HOME BUILDING MATERIALS ───────────────────────────────────────────────
    ("ASIANPAINT",  "Consumer", "Paints"),
    ("BERGEPAINT",  "Consumer", "Paints"),
    ("KANSAINER",   "Consumer", "Paints"),
    ("INDIAGLYCOL", "Chemicals", "Specialty Chemicals"),
    ("PIDILITIND",  "Consumer", "Adhesives"),
    ("FEVICOL",     "Consumer", "Adhesives"),
    ("SHALPAINTS",  "Consumer", "Paints"),
    ("CENTURYPLY",  "Consumer", "Plywood & Laminates"),
    ("GREENPANEL",  "Consumer", "Plywood & Laminates"),
    ("GREENLAMIND", "Consumer", "Plywood & Laminates"),
    ("KITEX",       "Textiles", "Children Garments"),
    ("CERA",        "Consumer", "Sanitaryware"),
    ("HINDWARE",    "Consumer", "Sanitaryware"),
    ("KAJARIA",     "Consumer", "Tiles"),
    ("ORIENTBELL",  "Consumer", "Tiles"),
    ("SOMANY",      "Consumer", "Tiles"),
    ("ASTRAL",      "Infra", "Pipes & Fittings"),
    ("SUPREMEIND",  "Packaging", "Packaging - Plastics"),
    ("NILKAMAL",    "Consumer", "Plastics & Furniture"),
    ("APOLLOPIPES", "Infra", "Pipes & Fittings"),
    ("FINOLEX",     "Cables", "Cables & Wires"),
    ("PRINCEPIPE",  "Infra", "Pipes & Fittings"),

    # ── AGRI & FERTILIZERS ───────────────────────────────────────────────────
    ("UPL",         "Agri", "Agro Chemicals"),
    ("PIIND",       "Agri", "Agro Chemicals"),
    ("BAYER",       "Agri", "Agro Chemicals"),
    ("SUMICHEM",    "Agri", "Agro Chemicals"),
    ("HERANBA",     "Agri", "Agro Chemicals"),
    ("ASTECLIFE",   "Agri", "Agro Chemicals"),
    ("COROMANDEL",  "Agri", "Fertilizers"),
    ("GNFC",        "Agri", "Fertilizers"),
    ("CHAMBAL",     "Agri", "Fertilizers"),
    ("NFL",         "Agri", "Fertilizers"),
    ("RCF",         "Agri", "Fertilizers"),
    ("TATACHEM",    "Chemicals", "Specialty Chemicals"),
    ("GUJFLUORO",   "Chemicals", "Specialty Chemicals"),
    ("AVANTIFEED",  "Agri", "Aquaculture"),
    ("WATERBASE",   "Agri", "Aquaculture"),
    ("APEX",        "Agri", "Aquaculture"),
    ("VENKYS",      "Agri", "Poultry"),
    ("SAKTHI",      "Agri", "Food Products"),
    ("KRBL",        "Agri", "Rice Products"),
    ("LTFOODS",     "Agri", "Rice Products"),
    ("RUCHI",       "Agri", "Edible Oils"),
    ("ADANITRANS",  "Energy", "Power Transmission"),
    ("PATANJALI",   "FMCG", "FMCG - HPC"),
    ("GODREJAGRO",  "Agri", "Agro Chemicals"),

    # ── PACKAGING ────────────────────────────────────────────────────────────
    ("UFLEX",       "Packaging", "Flexible Packaging"),
    ("HUHTAMAKI",   "Packaging", "Packaging - Paper"),
    ("MRPL",        "Energy", "Oil Refining"),
    ("MOLD-TEK",    "Packaging", "Packaging - Rigid"),
    ("MOLDTKPAC",   "Packaging", "Packaging - Rigid"),
    ("TATACOFFEE",  "FMCG", "FMCG - Foods"),
    ("SPECIALITY",  "Packaging", "Packaging - Paper"),
    ("NMSPACK",     "Packaging", "Packaging - Rigid"),
    ("PANACEA",     "Pharma", "Pharma Packaging"),

    # ── TEXTILES ─────────────────────────────────────────────────────────────
    ("PAGEIND",     "Consumer", "Innerwear & Hosiery"),
    ("WELSPUN",     "Textiles", "Home Textiles"),
    ("TRIDENT",     "Textiles", "Home Textiles"),
    ("ALOKIND",     "Textiles", "Synthetic Textiles"),
    ("SUTLEJ",      "Textiles", "Synthetic Textiles"),
    ("RAYMOND",     "Textiles", "Suiting & Fabric"),
    ("ARVIND",      "Textiles", "Denim & Fabric"),
    ("VARDHMAN",    "Textiles", "Yarn & Fabric"),
    ("NITIN",       "Textiles", "Yarn & Fabric"),
    ("SPENTEX",     "Textiles", "Yarn & Fabric"),
    ("GARMENTSIND", "Textiles", "Garments"),
    ("GOKEX",       "Textiles", "Cotton / Agri"),
    ("RSWM",        "Textiles", "Yarn & Fabric"),
    ("BOMBAYDY",    "Textiles", "Home Textiles"),
    ("HIMATSEIDE",  "Textiles", "Synthetic Textiles"),
    ("SPORTKING",   "Textiles", "Yarn & Fabric"),
    ("SIYARAM",     "Textiles", "Suiting & Fabric"),
    ("KPR",         "Textiles", "Garments"),
    ("KPRMILL",     "Textiles", "Garments"),
    ("GOKALDAS",    "Textiles", "Garments"),
    ("SAPPHIREFD",  "Consumer", "Food Products"),

    # ── MEDIA & ENTERTAINMENT ────────────────────────────────────────────────
    ("ZEEL",        "Consumer", "Broadcasting"),
    ("SUNTV",       "Consumer", "Broadcasting"),
    ("PVRINOX",     "Consumer", "Multiplex"),
    ("INOXLEISUR",  "Consumer", "Multiplex"),
    ("TVTODAY",     "Consumer", "Media & Entertainment"),
    ("NDTV",        "Consumer", "Media & Entertainment"),
    ("NETWORK18",   "Consumer", "Broadcasting"),
    ("BALAJITELE",  "Consumer", "Broadcasting"),
    ("HATHWAY",     "Telecom", "Cable TV & Broadband"),
    ("YATRA",       "Consumer", "Travel & Tourism"),
    ("IXIGO",       "Internet", "Travel Tech"),
    ("EASEMYTRIP",  "Internet", "Travel Tech"),
    ("MAKEMYTRIP",  "Internet", "Travel Tech"),

    # ── LOGISTICS & SHIPPING ─────────────────────────────────────────────────
    ("GMDCLTD",     "Metals", "Iron Ore"),
    ("ESGL",        "Shipping", "Shipping"),
    ("SCI",         "Shipping", "Shipping"),
    ("GE SHIPPING", "Shipping", "Shipping"),
    ("GESHIP",      "Shipping", "Shipping"),
    ("SEACOAST",    "Shipping", "Shipping"),
    ("SHREYAS",     "Shipping", "Container Shipping"),
    ("TRANSWORLD",  "Shipping", "Shipping"),
    ("ADANIPORTS",  "Infra", "Ports"),
    ("GVKPIL",      "Infra", "Ports"),
    ("JSW",         "Infra", "Ports"),
    ("CONCOR",      "Shipping", "Rail Logistics"),
    ("SNOWMAN",     "Infra", "Cold Chain Logistics"),
    ("ALLCARGO",    "Infra", "Logistics"),
    ("GATI",        "Infra", "Logistics"),
    ("DELHIVERY",   "Shipping", "Logistics"),
    ("BLUEDART",    "Shipping", "Express Logistics"),
    ("DTDC",        "Infra", "Logistics"),
    ("SAFEXPRESS",  "Infra", "Logistics"),

    # ── TELECOM ──────────────────────────────────────────────────────────────
    ("BHARTIARTL",  "Telecom", "Telecom Services"),
    ("IDEA",        "Telecom", "Telecom Services"),
    ("HFCL",        "Cables", "Optical Fiber Cables"),
    ("STLTECH",     "Cables", "Optical Fiber Cables"),
    ("TEJAS",       "Telecom", "Optical Networking"),
    ("VINDHYATEL",  "Telecom", "Telecom Infrastructure"),
    ("BSNL",        "Telecom", "Telecom Services"),

    # ── HOSPITALS / DIAGNOSTICS (recently listed IPOs) ───────────────────────
    ("YATHARTH",    "Pharma", "Hospitals"),
    ("MEDANTA",     "Pharma", "Hospitals"),
    ("CONCORD",     "Pharma", "Hospitals"),
    ("VIJAYA",      "Pharma", "Diagnostics"),
    ("SUVRDP",      "Pharma", "Diagnostics"),
    ("KRSNAA",      "Pharma", "Diagnostics"),
    ("HEALTHSRC",   "Pharma", "Diagnostics"),

    # ── IPOs 2023-2026 ────────────────────────────────────────────────────────
    ("NETWEB",      "IT", "Data Center Servers"),
    ("MAPMYINDIA",  "IT", "Geospatial & Maps"),
    ("LATENTVIEW",  "IT", "Data Analytics"),
    ("RATEGAIN",    "IT", "SaaS"),
    ("IXIGO",       "Internet", "Travel Tech"),
    ("SWIGGY",      "Internet", "Food Delivery"),
    ("NSDL",        "Financials", "Capital Markets"),
    ("WAAREEENER",  "Renewable", "Solar Modules"),
    ("ACMESOLAR",   "Renewable", "Solar Power"),
    ("SAGILITY",    "IT", "BPO & KPO"),
    ("HYUNDAI",     "Auto", "Auto OEM - 4W"),
    ("OLARIDER",    "Auto", "Auto OEM - EV"),
    ("AFCONS",      "Infra", "Construction EPC"),
    ("GARUDA",      "Consumer", "Aviation"),
    ("INDEGENE",    "IT", "Healthcare IT"),
    ("ARISINFRA",   "Infra", "Construction Materials"),
    ("INVENTURUS",  "IT", "Healthcare IT"),
    ("AETHER",      "Chemicals", "Specialty Chemicals"),
    ("COMSYN",      "Chemicals", "Specialty Chemicals"),
    ("DEEPINDS",    "Chemicals", "Specialty Chemicals"),
    ("SYRMA",       "Electronics", "Electronic Components"),
    ("KAYNES",      "Electronics", "Electronic Components"),
    ("AVALON",      "Electronics", "Electronic Components"),
    ("CELLO",       "Consumer", "Plastics & Furniture"),
    ("DRONEACHARYA","Defense", "Drones"),
    ("AEROFLEX",    "Electronics", "Electronic Components"),
    ("KRN",         "Cap Goods", "Heat Exchangers"),
    ("MTARTECH",    "Cap Goods", "Precision Engineering"),
    ("CENTUM",      "Electronics", "Electronic Components"),
    ("SARDAEN",     "Metals", "Steel"),
    ("TATAMETALI",  "Metals", "Steel Pipes"),
    ("JAIBALAJI",   "Metals", "Steel"),
    ("ELECTHERM",   "Cap Goods", "Industrial Furnaces"),
    ("WABCO",       "Auto", "Auto Ancillaries"),
    ("ZF",          "Auto", "Auto Ancillaries"),
    ("BREMBO",      "Auto", "Auto Ancillaries"),
    ("MINDA",       "Auto", "Auto Ancillaries"),
    ("UNO MINDA",   "Auto", "Auto Ancillaries"),
    ("UNOMINDA",    "Auto", "Auto Ancillaries"),
    ("SAMVARDHANA", "Auto", "Auto Ancillaries"),
    ("SANDHAR",     "Auto", "Auto Ancillaries"),
    ("JMT",         "Auto", "Auto Ancillaries"),
    ("VARUN",       "Auto", "Auto Ancillaries"),
    ("KDDL",        "Consumer", "Watches & Jewellery"),
    ("AMBER",       "Electronics", "Electronic Components"),
    ("DIXON",       "Electronics", "Electronic Components"),
    ("ELIN",        "Electronics", "Electronic Components"),
    ("PGEL",        "Electronics", "Electronic Components"),
    ("SGIL",        "Electronics", "Electronic Components"),
    ("SAHASRA",     "Electronics", "Electronic Manufacturing"),
    ("TEJAS",       "Telecom", "Optical Networking"),
    ("MACPOWER",    "Cap Goods", "Machine Tools"),
    ("JYOTIRES",    "Auto", "Auto Ancillaries"),
    ("ASAHIINDIA",  "Auto", "Auto Ancillaries"),
    ("SUPRAJIT",    "Auto", "Auto Ancillaries"),
    ("SHARDACROP",  "Agri", "Agro Chemicals"),
    ("DHANUKA",     "Agri", "Agro Chemicals"),
    ("BHARAT1",     "Auto", "Auto Ancillaries"),
    ("ECLERX",      "IT", "BPO & KPO"),

    # ── ADDITIONAL SUGAR/ETHANOL ──────────────────────────────────────────────
    ("RENUKA",      "Sugar", "Sugar"),
    ("TRIVENI",     "Sugar", "Sugar"),
    ("BALRAMCHIN",  "Sugar", "Sugar"),
    ("DALMIASUG",   "Sugar", "Sugar"),
    ("DHAMPURSUG",  "Sugar", "Sugar"),
    ("AVADHSUGAR",  "Sugar", "Sugar"),
    ("MAWANASUG",   "Sugar", "Sugar"),
    ("UTTAMSUGAR",  "Sugar", "Sugar"),
    ("DHAMPUR",     "Sugar", "Sugar"),
    ("DWARKESH",    "Sugar", "Sugar"),
    ("PRAJIND",     "Sugar", "Ethanol & Sugar"),
    ("SHREERENUKA", "Sugar", "Sugar"),
    ("UGARSUGAR",   "Sugar", "Sugar"),
    ("DHARANI",     "Sugar", "Sugar"),
    ("SIMBHAOLI",   "Sugar", "Sugar"),
    ("KMSUGAR",     "Sugar", "Sugar"),
    ("EID",         "Sugar", "Sugar"),
    ("EIDPARRY",    "Sugar", "Sugar"),

    # ── PSU BANKS (additional) ────────────────────────────────────────────────
    ("BANKINDIA",   "Banking", "PSU Banks"),
    ("CENTRALBK",   "Banking", "PSU Banks"),
    ("INDIANB",     "Banking", "PSU Banks"),
    ("IOB",         "Banking", "PSU Banks"),
    ("MAHABANK",    "Banking", "PSU Banks"),
    ("UCO",         "Banking", "PSU Banks"),
    ("JKBANK",      "Banking", "Regional Banks"),
    ("SOUTHBNK",    "Banking", "Regional Banks"),
    ("UJJIVANSFB",  "Banking", "Small Finance Banks"),
    ("KARNATKABANK","Banking", "Regional Banks"),
    ("YESBANK",     "Banking", "Private Banks"),

    # ── SILVER, GOLD, ALUMINUM, COPPER (metals rally theme) ──────────────────
    ("MCX",         "Financials", "Capital Markets"),
    ("MANAKSTEEL",  "Metals", "Steel"),
    ("ISMT",        "Metals", "Steel Pipes"),
    ("GALLANTT",    "Metals", "Steel"),
    ("ABHISHEK",    "Metals", "Steel"),
    ("JSPL",        "Metals", "Steel"),
    ("GOVAL",       "Metals", "Steel"),
    ("SUNFLAG",     "Metals", "Steel"),
    ("MUKANDFIN",   "Metals", "Steel"),
    ("HISAR",       "Metals", "Steel"),
    ("FACORALL",    "Metals", "Aluminium"),
    ("HINDALCOIND", "Metals", "Aluminium"),
    ("VEDANTA",     "Metals", "Diversified Metals"),
    ("STERLITE",    "Metals", "Copper"),
    ("HINDUCOPPER", "Metals", "Copper"),
    ("AURIONPRO",   "IT", "Fintech Software"),
]

added = 0
upgraded = 0
for entry in NEW_STOCKS:
    t, sector, industry = entry[0].upper().strip(), entry[1], entry[2]
    if not t:
        continue
    if t not in existing:
        existing[t] = {"nse_ticker": t, "sector": sector, "industry": industry, "notes": ""}
        added += 1
    elif existing[t].get("sector","") in ("","Other") or existing[t].get("industry","") in ("","Other"):
        existing[t]["sector"] = sector
        existing[t]["industry"] = industry
        upgraded += 1

sorted_rows = sorted(existing.values(), key=lambda r: r.get("nse_ticker","").upper())
with open(CSV, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    writer.writerows(sorted_rows)

print(f"Added: {added}  Upgraded: {upgraded}  Final total: {len(sorted_rows)}")
by_sector = Counter(r.get("sector","") for r in sorted_rows)
print("\nSector distribution:")
for sec, cnt in by_sector.most_common(30):
    print(f"  {sec:35s} {cnt:4d}")
print(f"\nTotal unique industries: {len(Counter(r.get('industry','') for r in sorted_rows))}")

