#!/usr/bin/env python3
"""
expand_taxonomy.py
Add ~500 missing NSE/BSE stocks to nse_stock_taxonomy.csv
"""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV  = ROOT / "data" / "nse_stock_taxonomy.csv"

NEW_STOCKS = [
    # ── BANKING ─────────────────────────────────────────────────────────────
    ("BANKINDIA","Banking","PSU Banks"),
    ("CENTRALBNK","Banking","PSU Banks"),
    ("INDIANB","Banking","PSU Banks"),
    ("IOB","Banking","PSU Banks"),
    ("MAHABANK","Banking","PSU Banks"),
    ("UCO","Banking","PSU Banks"),
    ("JKBANK","Banking","Regional Banks"),
    ("SOUTHBNK","Banking","Regional Banks"),
    ("TMBBANK","Banking","Regional Banks"),
    ("UJJIVANSFB","Banking","Small Finance Banks"),
    ("KARNATKABANK","Banking","Regional Banks"),
    ("SARASWATCO","Banking","Regional Banks"),
    ("LAKSHMIBANK","Banking","Regional Banks"),
    ("LAKSHVIL","Banking","Regional Banks"),
    ("YESBANK","Banking","Private Banks"),
    ("IDFC","Banking","Private Banks"),
    ("PNBHOUSING","Financials","Housing Finance"),
    ("IBULHSGFIN","Financials","Housing Finance"),
    ("HOMEFIRST","Financials","Housing Finance"),
    ("BAJAJHFL","Financials","Housing Finance"),
    ("ABCAPITAL","Financials","NBFC"),
    ("GODIGIT","Financials","Non-Life Insurance"),
    ("MFSL","Financials","Insurance & Finance"),
    ("TATAINVEST","Financials","NBFC"),
    ("GODREJFIN","Financials","NBFC"),
    ("STFC","Financials","Vehicle Finance"),
    ("SCUF","Financials","Vehicle Finance"),
    ("BHFIN","Financials","Consumer Finance"),
    ("TATAINVEST","Financials","NBFC"),
    ("GRUH","Financials","Housing Finance"),
    ("CENTRALBK","Banking","PSU Banks"),
    ("JANATA","Banking","Regional Banks"),
    ("LAKSHVILAS","Banking","Regional Banks"),

    # ── AUTO ─────────────────────────────────────────────────────────────────
    ("BAJAJAUT","Auto","Auto OEM - 2W"),
    ("BOSCH","Auto","Auto Ancillaries"),
    ("SONACOMS","Auto","Auto Ancillaries"),
    ("BALKRISIND","Auto","Tyres"),
    ("APOLLOTYRE","Auto","Tyres"),
    ("MRF","Auto","Tyres"),
    ("CEATLTD","Auto","Tyres"),
    ("GABRIEL","Auto","Auto Ancillaries"),
    ("JAMNA","Auto","Auto Ancillaries"),
    ("IGARASHI","Auto","Auto Ancillaries"),
    ("ASAHIINDIA","Auto","Auto Ancillaries"),
    ("GREAVESCOT","Auto","Engines & Compressors"),
    ("MAHINDCIE","Auto","Metal Forgings & Castings"),
    ("VARROC","Auto","Auto Ancillaries"),
    ("BFUTILITIE","Auto","Auto Ancillaries"),
    ("KALYANI","Metals","Metal Forgings & Castings"),
    ("HERO","Auto","Auto OEM - 2W"),
    ("HEROHONDA","Auto","Auto OEM - 2W"),
    ("SML","Auto","Auto OEM - CV"),
    ("TTMT","Auto","Auto OEM - 4W"),
    ("MAHSCOOTER","Auto","Auto OEM - 2W"),
    ("KINETIC","Auto","Auto OEM - 2W"),
    ("AMTEK","Metals","Metal Forgings & Castings"),
    ("SCHAEFFLER","Auto","Bearings"),
    ("SKFINDIA","Auto","Bearings"),
    ("TIMKEN","Auto","Bearings"),

    # ── CEMENT ───────────────────────────────────────────────────────────────
    ("ULTRACEMCO","Infra","Cement"),
    ("SHREECEM","Infra","Cement"),
    ("BIRLACORPN","Infra","Cement"),
    ("HEIDELBERG","Infra","Cement"),
    ("DALMIACE","Infra","Cement"),
    ("DALMIACEMB","Infra","Cement"),
    ("STARCMT","Infra","Cement"),
    ("PRISMJOHNSN","Infra","Cement"),
    ("JKIL","Infra","Cement"),
    ("SANGHI","Infra","Cement"),
    ("RAMCOCEM","Infra","Cement"),
    ("KESORAMIND","Infra","Cement"),
    ("SAURASHCEM","Infra","Cement"),

    # ── PIPES & FITTINGS ─────────────────────────────────────────────────────
    ("PRINCEPIPE","Infra","Pipes & Fittings"),
    ("ASTRAL","Infra","Pipes & Fittings"),
    ("FINOLEX","Infra","Pipes & Fittings"),
    ("SUPREME","Packaging","Packaging - Plastics"),
    ("NILKAMAL","Consumer","Plastics & Furniture"),
    ("APOLLOPIPES","Infra","Pipes & Fittings"),
    ("PLASTIBLEN","Infra","Pipes & Fittings"),

    # ── TELECOM ──────────────────────────────────────────────────────────────
    ("BHARTIARTL","Telecom","Telecom Services"),
    ("IDEA","Telecom","Telecom Services"),
    ("RAILTEL","Telecom","Telecom Infrastructure"),
    ("TATACOMM","Telecom","Telecom Services"),
    ("TTML","Telecom","Telecom Services"),
    ("INDUS","Telecom","Telecom Infrastructure"),
    ("GTLINFRA","Telecom","Telecom Infrastructure"),

    # ── OIL & GAS ────────────────────────────────────────────────────────────
    ("PETRONET","Energy","Gas Distribution"),
    ("IGL","Energy","Gas Distribution"),
    ("MGL","Energy","Gas Distribution"),
    ("GUJARATGAS","Energy","Gas Distribution"),
    ("GSPL","Energy","Gas Distribution"),
    ("ATGL","Energy","Gas Distribution"),
    ("CASTROL","Energy","Petroleum Products"),
    ("HINDOILEXP","Energy","Oil & Gas"),
    ("OIL","Energy","Oil & Gas"),
    ("GUJNREGAS","Energy","Gas Distribution"),
    ("PTCIND","Energy","Power Trading"),
    ("INDIAGRID","Energy","Power Transmission"),

    # ── POWER ────────────────────────────────────────────────────────────────
    ("NHPC","Energy","Power Generation"),
    ("SJVN","Energy","Power Generation"),
    ("KALPATPOWR","Energy","Power Transmission"),
    ("ORIENTGREEN","Renewable","Wind Energy"),
    ("WEBSOL","Renewable","Solar Panels"),
    ("KPCL","Energy","Power Generation"),
    ("WEBSOL","Renewable","Solar Panels"),
    ("NPTC","Energy","Power Generation"),

    # ── MEDIA & ENTERTAINMENT ────────────────────────────────────────────────
    ("ZEEL","Consumer","Media & Entertainment"),
    ("SUNTV","Consumer","Media & Entertainment"),
    ("PVRINOX","Consumer","Multiplex"),
    ("TV18BRDCST","Consumer","Media & Entertainment"),
    ("NETWORK18","Consumer","Media & Entertainment"),
    ("HATHWAY","Telecom","Cable TV & Broadband"),  # Hathway = cable TV & broadband provider; NOT Consumer sector
    ("SAREGAMA","Consumer","Music & Media"),
    ("TIPSINDLTD","Consumer","Music & Media"),
    ("INOXLEIS","Consumer","Multiplex"),
    ("NXTDIGITAL","Telecom","Cable TV"),  # NXTDIGITAL = cable TV distribution; NOT Consumer
    ("GTPL","Telecom","Cable TV & Broadband"),  # GTPL Hathway = cable & broadband; NOT Consumer

    # ── PHARMA / HEALTHCARE ──────────────────────────────────────────────────
    ("ABBOTINDIA","Pharma","Pharma Formulations"),
    ("PFIZER","Pharma","Pharma Formulations"),
    ("GLAXO","Pharma","Pharma Formulations"),
    ("SANOFI","Pharma","Pharma Formulations"),
    ("JBCHEPHARM","Pharma","Pharma Formulations"),
    ("SUVENPHARM","Pharma","Pharma API"),
    ("MANKIND","Pharma","Pharma Formulations"),
    ("WOCKPHARMA","Pharma","Pharma Formulations"),
    ("WINDLAS","Pharma","Pharma Contract Mfg"),
    ("DIVI","Pharma","Pharma API"),
    ("KIMS","Pharma","Hospitals"),
    ("MAXHEALTH","Pharma","Hospitals"),
    ("ASTER","Pharma","Hospitals"),
    ("HCG","Pharma","Hospitals"),
    ("HEALTHSPRING","Pharma","Healthcare IT"),
    ("AARTIDRUGS","Pharma","Pharma API"),
    ("SMRUTHIORG","Pharma","Pharma API"),
    ("PARABDRUGS","Pharma","Pharma API"),
    ("SUPRIYA","Pharma","Pharma API"),
    ("ERIS","Pharma","Pharma Formulations"),
    ("CAMSONBIO","Pharma","Healthcare Services"),
    ("BLUEBLOOD","Pharma","Pharma API"),
    ("ELIXIR","Pharma","Pharma API"),

    # ── CHEMICALS ────────────────────────────────────────────────────────────
    ("DEEPAKNITR","Chemicals","Specialty Chemicals"),
    ("AARTIIND","Chemicals","Specialty Chemicals - Pharma"),
    ("IOLCP","Chemicals","Specialty Chemicals"),
    ("LXCHEM","Chemicals","Specialty Chemicals"),
    ("CHEMCON","Chemicals","Specialty Chemicals"),
    ("FAIRCHEM","Chemicals","Specialty Chemicals"),
    ("PAUSHAKLTD","Chemicals","Specialty Chemicals - Fluorine"),
    ("KICL","Chemicals","Specialty Chemicals"),
    ("TATACHEMICAL","Chemicals","Specialty Chemicals - Alkali"),
    ("GUJFLUORO","Chemicals","Specialty Chemicals - Fluorine"),
    ("JUBILANTIND","Chemicals","Specialty Chemicals"),
    ("BHAGERIA","Chemicals","Specialty Chemicals - Dyes"),
    ("ASAHISONGI","Chemicals","Specialty Chemicals"),
    ("SOLUTIONK","Chemicals","Specialty Chemicals"),
    ("FINEOTEX","Chemicals","Specialty Chemicals"),
    ("AARTISURF","Chemicals","Specialty Chemicals"),
    ("APCOTEXIND","Chemicals","Specialty Chemicals"),
    ("GHCL","Chemicals","Specialty Chemicals - Alkali"),
    ("IGPL","Chemicals","Industrial Gases"),

    # ── FMCG ─────────────────────────────────────────────────────────────────
    ("RADICO","FMCG","FMCG - Beverages"),
    ("UNITDSPR","FMCG","FMCG - Beverages"),
    ("TILIND","FMCG","FMCG - Beverages"),
    ("PGHH","FMCG","FMCG - Personal Care"),
    ("GODFRYPHLP","FMCG","Cigarettes"),
    ("TATACONSUM","FMCG","FMCG - Beverages"),
    ("MCDOWELL-N","FMCG","FMCG - Beverages"),
    ("VSTIND","FMCG","Cigarettes"),

    # ── CONSUMER ─────────────────────────────────────────────────────────────
    ("BAJAJELEC","Consumer","Consumer Electricals"),
    ("VGUARD","Consumer","Consumer Electricals"),
    ("ANCHOR","Consumer","Consumer Electricals"),
    ("JCHAC","Consumer","Air Conditioners"),
    ("MIRC","Consumer","Consumer Electronics"),
    ("WHIRLPOOL","Consumer","Consumer Appliances"),
    ("LLOYDS","Consumer","Consumer Appliances"),
    ("ORIENTELEC","Consumer","Consumer Electricals"),
    ("ZEEL","Consumer","Media & Entertainment"),

    # ── PACKAGING ────────────────────────────────────────────────────────────
    ("POLYPLEX","Packaging","Packaging - Films"),
    ("SUPREMEIND","Packaging","Packaging - Plastics"),
    ("MOLDTEK","Packaging","Packaging - Containers"),
    ("APEX","Packaging","Packaging - Laminates"),

    # ── METALS ───────────────────────────────────────────────────────────────
    ("STERLITE","Metals","Copper"),
    ("APL","Metals","Steel Pipes"),
    ("HISAR","Metals","Steel"),
    ("SHYAM","Metals","Steel"),
    ("HARIOM","Metals","Steel"),
    ("JSL","Metals","Steel"),
    ("RAMSARUP","Metals","Steel"),
    ("JAISWAL","Metals","Steel"),
    ("JAISWALNIC","Metals","Steel"),
    ("BALASORE","Metals","Steel"),
    ("MISHRA","Metals","Specialty Metals"),
    ("WELSPUNSP","Metals","Steel Pipes"),
    ("SURYA","Metals","Steel Pipes"),

    # ── CAPITAL GOODS ────────────────────────────────────────────────────────
    ("KIRILOSKAR","Cap Goods","Pumps & Compressors"),
    ("KIRLOSKAR","Cap Goods","Pumps & Compressors"),
    ("KIRILOSENG","Cap Goods","Pumps & Compressors"),
    ("TECHNO","Cap Goods","Heat Exchange & Boilers"),
    ("POWMECH","Cap Goods","EPC"),
    ("PATEL","Infra","EPC & Construction"),
    ("WALCHAND","Cap Goods","Engineering"),
    ("TEXRAIL","Cap Goods","Railway Equipment"),
    ("TITAGARH","Infra","Railway Equipment"),
    ("BHARAT","Cap Goods","Engineering"),
    ("RIIL","Cap Goods","Engineering"),
    ("ACI","Cap Goods","Engineering"),
    ("ANUP","Cap Goods","Engineering"),
    ("KECIL","Cap Goods","Engineering"),
    ("ESAB","Cap Goods","Engineering"),

    # ── IT / TECH ─────────────────────────────────────────────────────────────
    ("BHARTIARTL","IT","Telecom Services"),
    ("HEXAWARE","IT","IT Services"),
    ("BIRLASOFT","IT","IT Services"),
    ("CYIENT","IT","IT Engineering"),
    ("RAMCOIND","Infra","Building Materials"),  # Ramco Industries = fiber cement boards; Ramco Systems (RAMCOSYS) is the IT entity
    ("ZENSAR","IT","IT Services"),
    ("NIIT","IT","IT Education"),
    ("NIITTECH","IT","IT Services"),
    ("SASKEN","IT","IT Engineering"),
    ("NUCLEUS","IT","IT Products"),
    ("SUBEX","IT","IT Products"),
    ("ONMOBILE","IT","IT Products"),
    ("VAKRANGEE","IT","IT Services"),
    ("UNIINFO","IT","IT Services"),
    ("NETSOL","IT","IT Services"),
    ("ECLERX","IT","BPO / KPO"),
    ("MASTEK","IT","IT Services"),
    ("HCLINFOSYS","IT","IT Services"),
    ("INFOSYS","IT","IT Services"),
    ("KOTAK","Banking","Private Banks"),

    # ── ELECTRONICS ───────────────────────────────────────────────────────────
    ("FSL","Electronics","Semiconductors"),
    ("BOROSIL","Consumer","Glassware"),  # Borosil Limited = consumer glassware brand; NOT electronic components
    ("TEJAS","Electronics","Optical Networking"),

    # ── INFRA / RAILWAY ───────────────────────────────────────────────────────
    ("IRFC","Infra","Railway Finance"),
    ("RAILVIKAS","Infra","Railway Construction"),
    ("KNR","Infra","Roads & Highways"),
    ("GMRINFRA","Infra","Airports"),
    ("GVK","Infra","Airports"),
    ("JPASSOCIAT","Infra","EPC & Construction"),
    ("EMGDELTA","Infra","EPC & Construction"),

    # ── REAL ESTATE ───────────────────────────────────────────────────────────
    ("PURAVANKARA","RealEstate","Real Estate - Residential"),
    ("PHOENIXLTD","RealEstate","Real Estate - Commercial"),
    ("ARVINDSMRT","RealEstate","Real Estate - Residential"),
    ("DBREALTY","RealEstate","Real Estate - Residential"),
    ("INDIABULL","RealEstate","Real Estate - Residential"),
    ("MAHLIFE","RealEstate","Real Estate - Residential"),

    # ── INTERNET ──────────────────────────────────────────────────────────────
    ("RATEGAIN","Internet","Travel Tech"),
    ("CARTRADE","Internet","Automotive Marketplace"),
    ("EASEMYTRIP","Internet","Travel & Hospitality"),
    ("NYKAA","Internet","Beauty & Fashion Retail"),
    ("XPRESSBEES","Shipping","Last Mile Logistics"),
    ("TBOTECH","Internet","B2B Marketplace"),

    # ── TEXTILES ──────────────────────────────────────────────────────────────
    ("NAHAREXP","Textiles","Textiles - Spinning"),
    ("PAGEIND","Textiles","Textiles - Innerwear"),
    ("LUXIND","Textiles","Textiles - Innerwear"),
    ("VEDANT","Textiles","Apparel Retail"),
    ("MANYAVAR","Textiles","Apparel Retail"),
    ("ETHNIX","Textiles","Apparel Retail"),

    # ── DEFENCE ───────────────────────────────────────────────────────────────
    ("DATACUBE","Defense","Defense Electronics"),
    ("PREMIER","Defense","Defense"),

    # ── AGRI ──────────────────────────────────────────────────────────────────
    ("KSCL","Agri","Seeds & Agri"),
    ("WSFL","Agri","Edible Oils"),
    ("GOKUL","Agri","Edible Oils"),
    ("RUCHI","Agri","Edible Oils"),
    ("PATANJALIFO","Agri","FMCG - Foods"),
    ("EID","Sugar","Sugar"),
    ("EIDPARRY","Sugar","Sugar"),
    ("DHARANI","Sugar","Sugar"),
    ("GAEL","Agri","Agri Processing"),
    ("WATERBASE","Agri","Aquaculture / Shrimp Feed"),
    ("MCLEODRUS","Agri","Tea Plantations"),

    # ── SHIPPING ──────────────────────────────────────────────────────────────
    ("XPRESSBEES","Shipping","Last Mile Logistics"),

    # ── MISC ADDITIONS ────────────────────────────────────────────────────────
    ("TATASTEEL","Metals","Steel"),
    ("TATAMOTORS","Auto","Auto OEM - 4W"),
    ("TATAPOWER","Energy","Power Generation"),
    ("TATACHEM","Chemicals","Agri Chemicals & Fertilisers"),
    ("HINDUNILVR","FMCG","FMCG - Personal Care"),
    ("NESTLEIND","FMCG","FMCG - Foods"),
    ("BRITANNIA","FMCG","FMCG - Foods"),
    ("MARICO","FMCG","FMCG - Personal Care"),
    ("DABUR","FMCG","FMCG - Personal Care"),
    ("COLPAL","FMCG","FMCG - Personal Care"),
    ("WIPRO","IT","IT Services"),
    ("INFY","IT","IT Services"),
    ("HCLTECH","IT","IT Services"),
    ("TCS","IT","IT Services"),
    ("TECHM","IT","IT Services"),
    ("LTIM","IT","IT Services"),
    ("LTTS","IT","IT Engineering"),
    ("MPHASIS","IT","IT Services"),
    ("PERSISTENT","IT","IT Services"),
    ("COFORGE","IT","IT Services"),
    ("TATAELXSI","IT","IT Engineering"),
    ("HAVELLS","Consumer","Consumer Electricals"),
    ("CROMPTON","Consumer","Consumer Electricals"),
    ("BAJAJELECTR","Consumer","Consumer Electricals"),
    ("BLUESTAR","Consumer","Air Conditioners"),
    ("VOLTAS","Consumer","Air Conditioners"),
    ("SYMPHONY","Consumer","Air Coolers"),
    ("TITAN","Consumer","Jewelry & Watches"),
    ("ASIANPAINT","Consumer","Paints"),
    ("BERGEPAINT","Consumer","Paints"),
    ("AKZOINDIA","Consumer","Paints"),
    ("INDIGOPNTS","Consumer","Paints"),
    ("PIDILITIND","Consumer","Adhesives & Chemicals"),
    ("GODREJCP","FMCG","FMCG - Personal Care"),
    ("ITC","FMCG","FMCG - Foods"),
    ("BRITANNIA","FMCG","FMCG - Foods"),
    ("HDFCBANK","Banking","Private Banks"),
    ("ICICIBANK","Banking","Private Banks"),
    ("AXISBANK","Banking","Private Banks"),
    ("KOTAKBANK","Banking","Private Banks"),
    ("SBIN","Banking","PSU Banks"),
    ("PNB","Banking","PSU Banks"),
    ("CANBK","Banking","PSU Banks"),
    ("BANKBARODA","Banking","PSU Banks"),
    ("UNIONBANK","Banking","PSU Banks"),
    ("AUBANK","Banking","Small Finance Banks"),
    ("BANDHANBNK","Banking","Small Finance Banks"),
    ("EQUITASBNK","Banking","Small Finance Banks"),
    ("UJJIVAN","Banking","Small Finance Banks"),
    ("ESAFSFB","Banking","Small Finance Banks"),
    ("JANA","Banking","Small Finance Banks"),
    ("UTKARSHBNK","Banking","Small Finance Banks"),
    ("FEDERALBNK","Banking","Private Banks"),
    ("RBLBANK","Banking","Private Banks"),
    ("DCBBANK","Banking","Regional Banks"),
    ("KARURVYSYA","Banking","Regional Banks"),
    ("KTKBANK","Banking","Regional Banks"),
    ("INDUSINDBK","Banking","Private Banks"),
    ("IDFCFIRSTB","Banking","Private Banks"),
    ("HDFCLIFE","Financials","Life Insurance"),
    ("SBILIFE","Financials","Life Insurance"),
    ("ICICIPRU","Financials","Life Insurance"),
    ("MAXLIFE","Financials","Life Insurance"),
    ("ICICIGI","Financials","Non-Life Insurance"),
    ("NIACINDIA","Financials","Non-Life Insurance"),
    ("STARHEALTH","Financials","Health Insurance"),
    ("GICRE","Financials","Reinsurance"),
    ("NIACL","Financials","Non-Life Insurance"),
    ("NIARE","Financials","Reinsurance"),
    ("HDFCAMC","Financials","Asset Management"),
    ("NIPPONAMC","Financials","Asset Management"),
    ("ABSLAMC","Financials","Asset Management"),
    ("UTIAMC","Financials","Asset Management"),
    ("SBIMF","Financials","Asset Management"),
    ("CAMS","Financials","Financial Technology"),
    ("CDSL","Financials","Financial Technology"),
    ("KFINTECH","Financials","Financial Technology"),
    ("BSE","Financials","Capital Markets"),
    ("MCX","Financials","Capital Markets"),
    ("ANGELONE","Financials","Stock Broking"),
    ("ANANDRATHI","Financials","Capital Markets"),
    ("ICICISEC","Financials","Stock Broking"),
    ("5PAISA","Financials","Stock Broking"),
    ("MOFSL","Financials","Wealth Management"),
    ("MOTILALOFS","Financials","Wealth Management"),
    ("NUVAMA","Financials","Wealth Management"),
    ("JMFINANCIL","Financials","Wealth Management"),
    ("PFC","Financials","Power Finance"),
    ("RECLTD","Financials","Power Finance"),
    ("IREDA","Financials","Power Finance"),
    ("LICHSGFIN","Financials","Housing Finance"),
    ("REPCO","Financials","Housing Finance"),
    ("AAVAS","Financials","Housing Finance"),
    ("APTUS","Financials","Housing Finance"),
    ("CANFINHOME","Financials","Housing Finance"),
    ("MUTHOOTFIN","Financials","Gold Loans"),
    ("MANAPPURAM","Financials","Gold Loans"),
    ("IIFL","Financials","NBFC"),
    ("CHOLAFIN","Financials","Vehicle Finance"),
    ("M&MFIN","Financials","Vehicle Finance"),
    ("SHRIRAMFIN","Financials","Vehicle Finance"),
    ("CREDITACC","Financials","Microfinance"),
    ("SPANDANA","Financials","Microfinance"),
    ("RELIANCE","Energy","Oil & Gas"),
    ("ONGC","Energy","Oil & Gas"),
    ("IOC","Energy","Oil Refining"),
    ("BPCL","Energy","Oil Refining"),
    ("HINDPETRO","Energy","Oil Refining"),
    ("MRPL","Energy","Oil Refining"),
    ("GAIL","Energy","Gas Distribution"),
    ("ADANIGAS","Energy","Gas Distribution"),
    ("ADANIPOWER","Energy","Power Generation"),
    ("ADANIGREEN","Renewable","Renewable Energy"),
    ("ADANIPORTS","Infra","Ports & Logistics"),
    ("ADANIENT","Infra","Diversified Infra"),
    ("SUZLON","Renewable","Wind Energy"),
    ("INOXWIND","Renewable","Wind Energy"),
    ("WAAREEENER","Renewable","Solar Panels"),
    ("ACMESOLAR","Renewable","Solar IPP"),
    ("ADANIENSOL","Renewable","Solar IPP"),
    ("OLECTRA","Renewable","EV Vehicles"),
    ("HAL","Defense","Aerospace & Defense"),
    ("BEL","Defense","Defense Electronics"),
    ("GRSE","Defense","Shipbuilding"),
    ("COCHINSHIP","Defense","Shipbuilding"),
    ("MAZDOCK","Defense","Shipbuilding"),
    ("MTARTECH","Defense","Aerospace & Defense"),
    ("DYNAMATECH","Defense","Aerospace & Defense"),
    ("IDEAFORGE","Defense","Drones"),
    ("DATAPATTNS","Electronics","Defense Electronics"),
    ("SOLARIND","Defense","Defense - Ammunition"),
    ("SOLARBOMB","Defense","Defense - Ammunition"),
    ("GOCLCORP","Defense","Defense - Explosives"),
    ("NAGAFERT","Defense","Defense - Explosives"),
    ("DRONEACHARYA","Defense","Drones"),
    ("CENTUM","Electronics","Electronic Components"),
    ("SYRMA","Electronics","Electronic Components"),
    ("KAYNES","Electronics","Electronic Components"),
    ("DIXON","Consumer","Consumer Electronics EMS"),
    ("AMBER","Electronics","Consumer Electronics EMS"),
    ("POLYCAB","Cables","Cables & Wires"),
    ("KEI","Cables","Cables & Wires"),
    ("FINOLEX","Cables","Cables & Wires"),
    ("STLTECH","Cables","Optical Fiber Cables"),
    ("HFCL","Cables","Optical Fiber Cables"),
    ("VOLTAMP","Cap Goods","Transformers"),  # Voltamp Transformers = capital goods; NOT Cables
    ("NAVINFLUOR","Chemicals","Specialty Chemicals - Fluorine"),
    ("SRF","Chemicals","Specialty Chemicals"),
    ("FLUOROCHEM","Chemicals","Specialty Chemicals - Fluorine"),
    ("ALKYLAMINE","Chemicals","Specialty Chemicals"),
    ("NOCIL","Chemicals","Specialty Chemicals"),
    ("ATUL","Chemicals","Specialty Chemicals"),
    ("VINATI","Chemicals","Specialty Chemicals"),
    ("DEEPAKFERT","Chemicals","Agri Chemicals & Fertilisers"),
    ("GUJALKALI","Chemicals","Specialty Chemicals - Alkali"),
    ("DCW","Chemicals","Specialty Chemicals - Alkali"),
    ("PCBL","Chemicals","Carbon Black"),
    ("PRAJIND","Chemicals","Ethanol / Bio Energy"),
    ("PIDILITIND","Consumer","Adhesives & Chemicals"),
    ("TATASTEEL","Metals","Steel"),
    ("JSWSTEEL","Metals","Steel"),
    ("SAIL","Metals","Steel"),
    ("JSHL","Metals","Steel"),
    ("HINDALCO","Metals","Aluminium"),
    ("NALCO","Metals","Aluminium"),
    ("VEDL","Metals","Diversified Metals"),
    ("HINDCOPPER","Metals","Copper Mining"),
    ("HINDZINC","Metals","Zinc & Lead"),
    ("NMDC","Metals","Metal & Mining"),
    ("MOIL","Metals","Manganese Mining"),
    ("GRAPHITE","Metals","Graphite Electrodes"),
    ("HEG","Metals","Graphite Electrodes"),
    ("PHILIPCARB","Metals","Graphite Electrodes"),
    ("BHARATFORG","Metals","Metal Forgings & Castings"),
    ("APLAPOLLO","Metals","Steel Pipes"),
    ("RATNAMANI","Metals","Steel Pipes"),
    ("WELCORP","Metals","Steel Pipes"),
    ("JINDALSAW","Metals","Steel Pipes"),
    ("GPIL","Metals","Steel - Sponge Iron"),
    ("HISARMETAL","Metals","Steel - Sponge Iron"),
    ("KIOCL","Metals","Iron Ore & Mining"),
    ("MIDHANI","Defense","Aerospace Alloys"),
    ("NMDC","Metals","Metal & Mining"),
    ("MSTCLTD","Metals","Metal & Mining"),
    ("L&T","Infra","EPC & Construction"),
    ("BHEL","Cap Goods","Heavy Engineering"),  # Bharat Heavy Electricals = capital goods; NOT Electronics sector
    ("THERMAX","Cap Goods","Heat Exchange & Boilers"),
    ("CUMMINSIND","Cap Goods","Engines & Compressors"),
    ("KIRLOSENG","Cap Goods","Pumps & Compressors"),
    ("ELGI","Cap Goods","Compressors"),
    ("KSB","Cap Goods","Pumps & Compressors"),
    ("AIAENG","Cap Goods","Cutting Tools"),
    ("KENNAMETAL","Cap Goods","Cutting Tools"),
    ("CARBORUNIV","Cap Goods","Cutting Tools"),
    ("PIXTRANS","Cap Goods","Power Transmission"),
    ("ISGEC","Cap Goods","Heavy Engineering"),
    ("SIEMENS","Cap Goods","Electrical Equipment"),
    ("ABB","Cap Goods","Electrical Equipment"),
    ("SCHNEIDER","Cap Goods","Electrical Equipment"),
    ("LOKESHMACH","Cap Goods","Machine Tools"),
    ("TIIL","Cap Goods","Textile Machinery"),
    ("PAHARPUR","Cap Goods","Heat Exchange & Boilers"),
    ("RITEFIL","Cap Goods","Filtration"),
    ("TRIVENIENG","Cap Goods","Engineering"),
    ("GRINDMASTER","Cap Goods","Grinders & Machines"),
    ("SUNPHARMA","Pharma","Pharma Formulations"),
    ("DRREDDY","Pharma","Pharma Formulations"),
    ("CIPLA","Pharma","Pharma Formulations"),
    ("LUPIN","Pharma","Pharma Formulations"),
    ("TORNTPHARM","Pharma","Pharma Formulations"),
    ("ALKEM","Pharma","Pharma Formulations"),
    ("GLENMARK","Pharma","Pharma Formulations"),
    ("IPCALAB","Pharma","Pharma Formulations"),
    ("AJANTPHARM","Pharma","Pharma Formulations"),
    ("NATCOPHARM","Pharma","Pharma Formulations"),
    ("DIVISLAB","Pharma","Pharma Formulations"),
    ("AUROPHARMA","Pharma","Pharma API"),
    ("GRANULES","Pharma","Pharma API"),
    ("LAURUSLABS","Pharma","Pharma API"),
    ("NEULANDLAB","Pharma","Pharma API"),
    ("BIOCON","Pharma","Pharma API"),
    ("SEQUENT","Pharma","Pharma API"),
    ("APOLLOHOSP","Pharma","Hospitals"),
    ("FORTIS","Pharma","Hospitals"),
    ("ASTERDM","Pharma","Hospitals"),
    ("NARAYANA","Pharma","Hospitals"),
    ("YATHARTH","Pharma","Hospitals"),
    ("RAINBOW","Pharma","Hospitals"),
    ("METROPOLIS","Pharma","Diagnostics"),
    ("DRLALPATH","Pharma","Diagnostics"),
    ("THYROCARE","Pharma","Diagnostics"),
    ("VIJAYALAB","Pharma","Diagnostics"),
    ("MEDPLUS","Pharma","Pharmacy Retail"),
    ("APOLLOPHARM","Pharma","Pharmacy Retail"),
    ("SHILPAMED","Pharma","Medical Devices"),
    ("POLYMED","Pharma","Medical Devices"),
    ("HESTER","Pharma","Veterinary & Animal Health"),
    ("ZOMATO","Internet","Food Delivery"),
    ("SWIGGY","Internet","Food Delivery"),
    ("NAUKRI","Internet","Online Recruitment"),
    ("INDIAMART","Internet","B2B Marketplace"),
    ("IRCTC","Internet","Travel & Hospitality"),
    ("PAYTM","Internet","Fintech"),
    ("INFIBEAM","Internet","Fintech"),
    ("POLICYBZR","Internet","Insurance Technology"),
    ("MAPMYINDIA","Internet","Digital Maps"),
    ("DELHIVERY","Internet","Last Mile Logistics"),
    ("M&M","Auto","Auto OEM - 4W"),
    ("MARUTI","Auto","Auto OEM - 4W"),
    ("TATAMOTORS","Auto","Auto OEM - 4W"),
    ("ESCORTS","Auto","Auto OEM - 4W"),
    ("EICHERMOT","Auto","Auto OEM - 4W"),
    ("HEROMOTOCO","Auto","Auto OEM - 2W"),
    ("TVSMOTOR","Auto","Auto OEM - 2W"),
    ("BAJAJAUT","Auto","Auto OEM - 2W"),
    ("ASHOKLEY","Auto","Auto OEM - CV"),
    ("FORCEMOT","Auto","Auto OEM - CV"),
    ("MOTHERSON","Auto","Auto Ancillaries"),
    ("MINDA","Auto","Auto Ancillaries"),
    ("MINDAIND","Auto","Auto Ancillaries"),
    ("BOSCH","Auto","Auto Ancillaries"),
    ("SCHAEFFLER","Auto","Bearings"),
    ("TIMKEN","Auto","Bearings"),
    ("EXIDEIND","Auto","Auto Batteries"),
    ("BALKRISIND","Auto","Tyres"),
    ("APOLLOTYRE","Auto","Tyres"),
    ("MRF","Auto","Tyres"),
    ("CEATLTD","Auto","Tyres"),
    ("ENDURANCE","Auto","Auto Ancillaries"),
    ("SUPRAJIT","Auto","Auto Ancillaries"),
    ("FIEM","Auto","Auto Ancillaries"),
    ("PRICOL","Auto","Auto Ancillaries"),
    ("SANSERA","Auto","Metal Forgings & Castings"),
    ("GNA","Auto","Metal Forgings & Castings"),
    ("SUNDRMFAST","Auto","Metal Forgings & Castings"),
    ("CRAFTSMAN","Auto","Metal Forgings & Castings"),
    ("JBMA","Auto","Metal Forgings & Castings"),
    ("MAHINDRACIE","Auto","Metal Forgings & Castings"),
    ("NELCAST","Metals","Metal Forgings & Castings"),
    ("SHRIPISTON","Auto","Metal Forgings & Castings"),
    ("DLF","RealEstate","Real Estate - Residential"),
    ("GODREJPROP","RealEstate","Real Estate - Residential"),
    ("BRIGADE","RealEstate","Real Estate - Residential"),
    ("PRESTIGE","RealEstate","Real Estate - Residential"),
    ("SOBHA","RealEstate","Real Estate - Residential"),
    ("MACROTECH","RealEstate","Real Estate - Residential"),
    ("OBEROIRLTY","RealEstate","Real Estate - Premium"),
    ("AJMERA","RealEstate","Real Estate - Residential"),
    ("SUNTECK","RealEstate","Real Estate - Residential"),
    ("ASHOKA","Infra","Roads & Highways"),
    ("IRB","Infra","Roads & Highways"),
    ("KNRCON","Infra","Roads & Highways"),
    ("HGINFRA","Infra","Roads & Highways"),
    ("CEIGALL","Infra","Roads & Highways"),
    ("PNC","Infra","Roads & Highways"),
    ("NBCC","Infra","Govt Construction"),
    ("PSPPROJECT","Infra","EPC & Construction"),
    ("RITES","Infra","Railway Consultancy"),
    ("IRCON","Infra","Railway Construction"),
    ("RVNL","Infra","Railway Construction"),
    ("AMBUJACEM","Infra","Cement"),
    ("INDIACEM","Infra","Cement"),
    ("JKCEMENT","Infra","Cement"),
    ("NUVOCO","Infra","Cement"),
    ("MANGLMCEM","Infra","Cement"),
    ("ADANIPORTS","Infra","Ports & Logistics"),
    ("GPPL","Infra","Ports & Logistics"),
    ("CONCOR","Shipping","Rail Logistics"),
    ("ALLCARGO","Shipping","Logistics"),
    ("BLUEDART","Shipping","Air Logistics"),
    ("TCI","Shipping","Road Logistics"),
    ("GESHIP","Shipping","Shipping"),
    ("SCI","Shipping","Shipping"),
    ("MAHLOG","Shipping","Logistics"),
    ("WELSPUNIND","Textiles","Textiles - Home"),
    ("TRIDENT","Textiles","Textiles - Home"),
    ("RAYMOND","Textiles","Textiles - Apparel"),
    ("ARVIND","Textiles","Textiles - Apparel"),
    ("GOKALDAS","Textiles","Textiles - Apparel"),
    ("KITEX","Textiles","Textiles - Apparel"),
    ("VARDHMAN","Textiles","Textiles - Spinning"),
    ("NITINSPIN","Textiles","Textiles - Spinning"),
    ("NAHARSPING","Textiles","Textiles - Spinning"),
    ("SPORTKING","Textiles","Textiles - Synthetic"),
    ("GARWARE","Textiles","Textiles - Technical"),
    ("HIMATSEIDE","Textiles","Textiles - Technical"),
    ("GRASIM","Textiles","Textiles - Viscose"),
    ("RUPA","Textiles","Textiles - Innerwear"),
    ("LUX","Textiles","Textiles - Innerwear"),
    ("DOLLAR","Textiles","Textiles - Innerwear"),
    ("STYLAMIND","Textiles","Textiles - Home"),
    ("PAGES","Textiles","Apparel Retail"),
    ("STYLEBAAZA","Textiles","Apparel Retail"),
    ("TRENT","Consumer","Apparel Retail"),
    ("AVANTIFEED","Agri","Aquaculture / Shrimp Feed"),
    ("VENKYS","Agri","Poultry & Agri"),
    ("KRBL","Agri","Rice / Agri"),
    ("PKTEA","Agri","Tea Plantations"),
    ("TIRUPATIFL","Agri","Flour Milling"),
    ("AVADHSUGAR","Sugar","Sugar"),
    ("DALMIASUG","Sugar","Sugar"),
    ("DEEDEV","Cap Goods","Industrial Piping & Pressure Vessels"),
    ("DHAMPUR","Sugar","Sugar"),
    ("DHAMPURSUG","Sugar","Sugar"),
    ("DWARKESH","Sugar","Sugar"),
    ("KMSUGAR","Sugar","Sugar"),
    ("MAWANASUG","Sugar","Sugar"),
    ("RENUKA","Sugar","Sugar"),
    ("TRIVENI","Sugar","Sugar"),
    ("UGARSUGAR","Sugar","Sugar"),
    ("UTTAMSUGAR","Sugar","Sugar"),
    ("SIMBHAOLI","Sugar","Sugar"),
    ("BALRAMCHIN","Sugar","Sugar"),
    ("RALLIS","Chemicals","Specialty Chemicals - Agri"),
    ("SUMICHEM","Chemicals","Specialty Chemicals - Agri"),
    ("DHANUKA","Chemicals","Specialty Chemicals - Agri"),
    ("PI","Chemicals","Specialty Chemicals - Agri"),
    ("UPL","Chemicals","Specialty Chemicals - Agri"),
    ("BAYER","Chemicals","Specialty Chemicals - Agri"),
    ("DEEPAKFERT","Chemicals","Agri Chemicals & Fertilisers"),
    ("PARADEEP","Chemicals","Agri Chemicals & Fertilisers"),
    ("TATACHEM","Chemicals","Agri Chemicals & Fertilisers"),
    ("ROSSARI","Chemicals","Specialty Chemicals - Fluorine"),
    ("AETHER","Chemicals","Specialty Chemicals"),
    ("CAMLIN","Chemicals","Specialty Chemicals"),
    ("CLEAN","Chemicals","Specialty Chemicals"),
    ("NEOGEN","Chemicals","Specialty Chemicals"),
    ("GALAXYSURF","Chemicals","Specialty Chemicals"),
    ("FINEORG","Chemicals","Specialty Chemicals"),
    ("COMSYN","Chemicals","Specialty Chemicals"),
    ("DEEPINDS","Chemicals","Specialty Chemicals"),
    ("AARTI","Chemicals","Specialty Chemicals"),
    ("SUDARSCHEM","Chemicals","Specialty Chemicals"),
    ("COLORMASTER","Chemicals","Specialty Chemicals - Dyes"),
    ("BEPL","Chemicals","Specialty Chemicals"),
    ("BASF","Chemicals","Specialty Chemicals"),
    ("AEGISLOG","Shipping","Logistics"),  # AEGIS Logistics = LPG/petroleum bulk liquid logistics; NOT chemicals
    ("LINCOLNCAP","Chemicals","Specialty Chemicals"),
    ("ATAM","Chemicals","Industrial Gases"),
    ("HINDUSTAN","Chemicals","Industrial Gases"),
    ("DENSATECH","Chemicals","Industrial Gases"),
    ("LINDE","Chemicals","Industrial Gases"),
    ("KEI","Cables","Cables & Wires"),
    ("CABINDIA","Cables","Cables & Wires"),
    ("PRECWIRE","Cables","Cables & Wires"),
    ("SUMEETINDS","Cables","Cables & Wires"),
    ("RR","Cables","Cables & Wires"),
    ("INDOTECH","Cables","Cables & Wires"),
    ("SPECTRUM","Cables","Cables & Wires"),
    ("OPTIEMUS","Cables","Optical Fiber Cables"),
    ("HALONIX","Electronics","Display & Lighting"),
    ("AEROFLEX","Electronics","Electronic Components"),
    ("KRN","Electronics","Electronic Components"),
    ("ADVAIT","Electronics","Electronic Components"),
    ("ELIN","Electronics","Electronic Components"),
    ("PGEL","Electronics","Electronic Components"),
    ("AVALON","Electronics","Electronic Components"),
    ("INOXINDIA","Cap Goods","Industrial Gases Equipment"),  # INOX India = cryogenic tanks/industrial gas storage; NOT electronic components
    ("ELCOMPCORP","Electronics","Electronic Components"),
    ("SGIL","Electronics","Electronic Components"),
    ("VIMTALABS","Pharma","Testing Labs"),  # Vimta Labs = pharma/food/water analytical testing lab; NOT electronic components
    ("MOSCHIP","Electronics","Semiconductors"),
    ("SPEL","Electronics","Semiconductors"),
    ("AXISCADES","Electronics","IT Engineering"),
    ("TDPOWERSYS","Cap Goods","Alternators"),  # TD Power Systems = generators & alternators; NOT Electronics
    ("POWERINDIA","Cap Goods","Electrical Equipment"),  # Hitachi Energy India = capital goods electrical equipment; NOT Electronics
    ("VOLTAMP","Cap Goods","Transformers"),  # Voltamp Transformers = capital goods; NOT Electronics
    ("BSE","Financials","Capital Markets"),
    ("SAMMAANCAP","Financials","Capital Markets"),
    ("ONELIFECAP","Financials","Capital Markets"),
    ("DBSTOCKBRO","Financials","Stock Broking"),
    ("GEOJITFSL","Financials","Stock Broking"),
    ("ARIHANTCAP","Financials","Stock Broking"),
    ("SMIFS","Financials","Stock Broking"),
    ("CHOICEIN","Financials","Stock Broking"),
    ("BIRLAMONEY","Financials","Wealth Management"),
    ("CRISIL","Financials","Financial Technology"),
    ("NSDL","Financials","Financial Technology"),
    ("BAJAJFINSV","Financials","Insurance & Finance"),
    ("CHOLAHLDNG","Financials","Insurance & Finance"),
    ("BAJFINANCE","Financials","Consumer Finance"),
    ("LTF","Financials","Consumer Finance"),
    ("IIFL","Financials","NBFC"),
    ("MANCREDIT","Financials","NBFC"),
    ("SBFC","Financials","NBFC"),
    ("TFCILTD","Financials","NBFC"),
    ("AHLUCONT","Packaging","Packaging - Containers"),
    ("EPL","Packaging","Packaging - Laminates"),
    ("EMMBI","Packaging","Packaging - Films"),
    ("JINDALPOLY","Packaging","Packaging - Films"),
    ("UFLEX","Packaging","Packaging - Films"),
    ("XPROINDIA","Packaging","Packaging - Films"),
    ("HUHTAMAKI","Packaging","Packaging - Laminates"),
    ("ORICONENT","Packaging","Packaging - Containers"),
    ("JKPAPER","Packaging","Paper & Packaging"),
    ("SESHAPAPER","Packaging","Paper & Packaging"),
    ("KANSAINER","Packaging","Packaging"),
    ("KALYANKJIL","Consumer","Gold Jewelry"),
    ("TITAN","Consumer","Jewelry & Watches"),
    ("SENCO","Consumer","Gold Jewelry"),
    ("THANGAMAYL","Consumer","Gold Jewelry"),
    ("KDDL","Consumer","Jewelry & Watches"),
    ("LENSKART","Consumer","Eyewear Retail"),
    ("TRENT","Consumer","Apparel Retail"),
    ("GREENPANEL","Consumer","Consumer"),
    ("GODREJIND","Consumer","Adhesives & Chemicals"),
    ("WHIRLPOOL","Consumer","Consumer Appliances"),
    ("ORIENTELEC","Consumer","Consumer Electricals"),
    ("VGUARD","Consumer","Consumer Electricals"),
    ("NYKAA","Internet","Beauty & Fashion Retail"),
    ("INFY","IT","IT Services"),
    ("WIPRO","IT","IT Services"),
    ("BSOFT","IT","IT Services"),
    ("CMSINFO","IT","IT Services"),
    ("DATAMATICS","IT","IT Services"),
    ("HAPPSTMNDS","IT","IT Services"),
    ("KPITTECH","IT","IT Services"),
    ("MASTEK","IT","IT Services"),
    ("MPHASIS","IT","IT Services"),
    ("NEWGEN","IT","IT Services"),
    ("NIINSYS","IT","IT Services"),
    ("NIITTECH","IT","IT Services"),
    ("NINSYS","IT","IT Services"),
    ("OFSS","IT","IT Services"),
    ("PERSISTENT","IT","IT Services"),
    ("SECURKLOUD","IT","IT Services"),
    ("TANLA","IT","IT Services"),
    ("TRIGYN","IT","IT Services"),
    ("ZENSARTECH","IT","IT Services"),
    ("INTELLECT","IT","IT Products"),
    ("RAMCOIND","Infra","Building Materials"),  # Ramco Industries = fiber cement/asbestos cement products; NOT IT (Ramco Systems/RAMCOSYS is the IT company)
    ("NUCLEUS","IT","IT Products"),
    ("SUBEX","IT","IT Products"),
    ("ONMOBILE","IT","IT Products"),
    ("LTTS","IT","IT Engineering"),
    ("CYIENT","IT","IT Engineering"),
    ("SASKEN","IT","IT Engineering"),
    ("AXISCADES","Electronics","IT Engineering"),
    ("ECLERX","IT","BPO / KPO"),
    ("NIIT","IT","IT Education"),
    ("APARINDS","Cables","Cables & Wires"),  # APAR Industries = electrical conductors, cables & transformer oils; NOT Auto sector
    ("LUMAXTECH","Auto","Auto Ancillaries"),
    ("TIINDIA","Auto","Auto Ancillaries"),
    ("TIMETECHNO","Auto","Auto Ancillaries"),
    ("SETCO","Auto","Auto Ancillaries"),
    ("RACL","Auto","Auto Ancillaries"),
    ("SONAMLTD","Auto","Auto Ancillaries"),
    ("SPAL","Auto","Auto Ancillaries"),
    ("SUBROS","Auto","Auto Ancillaries"),
    ("JAMNAAUTO","Auto","Auto Ancillaries"),
    ("CARRARO","Auto","Metal Forgings & Castings"),
    ("CIEINDIA","Auto","Metal Forgings & Castings"),
    ("AMARON","Auto","Auto Batteries"),
    ("ZF","Auto","Auto Ancillaries"),
    ("WHEELS","Auto","Auto Ancillaries"),
    ("BORORENEW","Auto","Auto"),
    ("GABRIEL","Auto","Auto Ancillaries"),
    ("ISGEC","Cap Goods","Heavy Engineering"),
    ("BHAGYANGR","Infra","Roads & Highways"),
    ("SADBHAV","Infra","Roads & Highways"),
    ("BHAGERIA","Chemicals","Specialty Chemicals - Dyes"),
    ("DCMSHRIRAM","Sugar","Agri Chemicals & Fertilisers"),
    ("AGROPHOS","Chemicals","Agri Chemicals & Fertilisers"),
    ("JAYAGROGN","Chemicals","Specialty Chemicals - Agri"),
    ("DEEPAKFERT","Chemicals","Agri Chemicals & Fertilisers"),
    ("DBOL","Other","Other"),
    ("TVSHLTD","Financials","Holding Company"),  # TVS Holdings = holding/investment company for TVS Group; NOT a bank
    ("INDOTHAI","Financials","Stock Broking"),  # Indo Thai Securities = stock brokerage firm; NOT a bank
    ("BIKAJI","FMCG","FMCG - Foods"),
    ("DEVYANI","FMCG","QSR"),
    ("JUBLFOOD","FMCG","QSR"),
    ("WESTLIFE","FMCG","QSR"),
    ("SAPPHIRE","FMCG","QSR"),
    ("VARUN","FMCG","FMCG - Beverages"),
    ("CCL","FMCG","FMCG - Beverages"),
    ("GMBREW","FMCG","FMCG - Beverages"),
    ("JYOTHYLAB","FMCG","FMCG - Personal Care"),
    ("BAJAJCON","FMCG","FMCG - Personal Care"),
    ("EMAMILTD","FMCG","FMCG - Personal Care"),
    ("GILLETTE","FMCG","FMCG - Personal Care"),
    ("COLPAL","FMCG","FMCG - Personal Care"),
    ("HONASA","FMCG","FMCG - Personal Care"),
    ("PRSMJOHNSN","FMCG","FMCG - Foods"),
    ("HNDFDS","FMCG","FMCG - Foods"),
    ("TRAVELFOOD","FMCG","FMCG - Foods"),
    ("ZYDUSWELL","FMCG","FMCG - Foods"),
    ("PATANJALI","Agri","FMCG - Foods"),
    ("VSTIND","FMCG","Cigarettes"),
    ("GODFRYPHLP","FMCG","Cigarettes"),
    ("ITC","FMCG","FMCG - Foods"),
]

# ── Read existing ──────────────────────────────────────────────────────────────
existing: dict[str, dict] = {}
fieldnames: list[str] = []
with open(CSV, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fieldnames = list(reader.fieldnames or ["nse_ticker","sector","industry","notes"])
    for row in reader:
        t = row.get("nse_ticker","").strip().upper()
        if t:
            existing[t] = dict(row)

added = 0
upgraded = 0
for ticker, sector, industry in NEW_STOCKS:
    t = ticker.strip().upper()
    if not t:
        continue
    if t not in existing:
        existing[t] = {"nse_ticker": t, "sector": sector, "industry": industry, "notes": ""}
        added += 1
    elif existing[t].get("sector","") in ("Other","") and sector not in ("Other",""):
        existing[t]["sector"] = sector
        existing[t]["industry"] = industry
        upgraded += 1

# Sort alphabetically
sorted_rows = sorted(existing.values(), key=lambda r: r.get("nse_ticker","").upper())

with open(CSV, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    writer.writerows(sorted_rows)

print(f"Added: {added}  Upgraded: {upgraded}  Total tickers: {len(sorted_rows)}")

# ── BATCH 2: Additional NSE/BSE stocks ───────────────────────────────────────
BATCH2 = [
    # ── BANKING ─────────────────────────────────────────────────────────────
    ("EQUITASBNK","Banking","Small Finance Banks"),
    ("SURYODAY","Banking","Small Finance Banks"),
    ("ESAFSFB","Banking","Small Finance Banks"),
    ("UTKARSHBNK","Banking","Small Finance Banks"),
    ("JSFB","Banking","Small Finance Banks"),
    ("CAPITALSFB","Banking","Small Finance Banks"),
    ("NAINITALBNK","Banking","Regional Banks"),
    ("DBCORP","Consumer","Media & Entertainment"),  # DB Corp = Dainik Bhaskar media group; NOT a bank
    ("DCBBANK","Banking","Private Banks"),
    ("RBLBANK","Banking","Private Banks"),
    ("CSBBANK","Banking","Private Banks"),
    ("TMKFINANCE","Financials","NBFC"),
    ("SBCL","Banking","Regional Banks"),

    # ── FINANCIALS / NBFC ───────────────────────────────────────────────────
    ("MANAPPURAM","Financials","Gold Loans"),
    ("MUTHOOTFIN","Financials","Gold Loans"),
    ("MUTHOOTCAP","Financials","Gold Loans"),
    ("IIFL","Financials","NBFC"),
    ("IIFLSEC","Financials","Stock Broking"),
    ("IDFCFIRSTB","Banking","Private Banks"),
    ("CREDITACC","Financials","Microfinance"),
    ("AROHAN","Financials","Microfinance"),
    ("SPANDANA","Financials","Microfinance"),
    ("FUSION","Financials","Microfinance"),
    ("NAVINFIN","Financials","Microfinance"),
    ("SATIN","Financials","Microfinance"),
    ("MAXFIN","Financials","NBFC"),
    ("HDFCAMC","Financials","Asset Management"),
    ("ABSLAMC","Financials","Asset Management"),
    ("NIPPONSEIMC","Financials","Asset Management"),
    ("UTIAMC","Financials","Asset Management"),
    ("ICICIPRAMC","Financials","Asset Management"),
    ("SUNDARMFIN","Financials","NBFC"),
    ("CHOLAFIN","Financials","NBFC"),
    ("LICI","Financials","Insurance"),
    ("GICRE","Financials","Insurance"),
    ("NIACL","Financials","Insurance"),
    ("ORIENTELC","Financials","Insurance"),
    ("ICICIlombrd","Financials","Insurance"),
    ("HDFCLIFE","Financials","Insurance"),
    ("SBILIFE","Financials","Insurance"),
    ("MAXLIFE","Financials","Insurance"),
    ("ABSLI","Financials","Insurance"),
    ("STARHEALTH","Financials","Insurance"),
    ("POLICYBZR","Internet","Fintech"),
    ("PAYTM","Internet","Fintech"),
    ("MOBIKWIK","Internet","Fintech"),
    ("INDIASHLTR","Financials","Housing Finance"),
    ("APTUS","Financials","Housing Finance"),
    ("HOMEFIRST","Financials","Housing Finance"),
    ("REPPRO","Financials","Stock Broking"),
    ("MOTILALOFS","Financials","Stock Broking"),
    ("ZERODHA","Financials","Stock Broking"),
    ("SMCGLOBAL","Financials","Stock Broking"),
    ("GEOJITFSL","Financials","Stock Broking"),
    ("EMKAY","Financials","Stock Broking"),

    # ── IT / TECHNOLOGY ─────────────────────────────────────────────────────
    ("LTIM","IT","IT Services"),
    ("COFORGE","IT","IT Services"),
    ("PERSISTENT","IT","IT Services"),
    ("KPIT","IT","IT Engineering"),
    ("BSOFT","IT","IT Services"),
    ("RATEGAIN","IT","SaaS"),
    ("MAPMYINDIA","IT","Geospatial Tech"),
    ("ROUTE","IT","IT Services"),
    ("MASTEK","IT","IT Services"),
    ("NIIT","IT","IT Training"),
    ("NIITMTS","IT","IT Training"),
    ("SAKSOFT","IT","IT Services"),
    ("QUICKHEAL","IT","Cybersecurity"),
    ("INFIBEAM","IT","E-Commerce Infra"),
    ("NETWEB","IT","IT Hardware"),
    ("BECTORFOOD","Consumer","Food Products"),
    ("XCHANGING","IT","IT Services"),
    ("ZENSAR","IT","IT Services"),
    ("BIRLASOFT","IT","IT Services"),
    ("SONATSOFTW","IT","IT Services"),
    ("CARERATING","Financials","Credit Rating"),
    ("CRISIL","Financials","Credit Rating"),
    ("ICRA","Financials","Credit Rating"),
    ("INDIAMART","Internet","B2B Marketplace"),
    ("NAUKRI","Internet","Job Portal"),
    ("JUSTDIAL","Internet","Local Search"),
    ("AFFLE","Internet","AdTech"),
    ("BIGBLOC","RealEstate","Building Materials"),
    ("TATAELXSI","IT","IT Engineering"),
    ("CYIENT","IT","IT Engineering"),
    ("MPHASIS","IT","IT Services"),
    ("HEXAWARE","IT","IT Services"),
    ("OFSS","IT","IT Products - Banking"),
    ("ECLERX","IT","BPO"),
    ("QUESS","IT","Staffing"),
    ("TEAMLEASE","IT","Staffing"),
    ("SIS","IT","Facility Management"),

    # ── PHARMACEUTICALS ─────────────────────────────────────────────────────
    ("IPCALAB","Pharma","Formulations"),
    ("GLAXO","Pharma","Formulations"),
    ("ABBOTINDIA","Pharma","Formulations"),
    ("PFIZER","Pharma","Formulations"),
    ("SANOFI","Pharma","Formulations"),
    ("NOVARTIS","Pharma","Formulations"),
    ("ASTRAZEN","Pharma","Formulations"),
    ("JBCHEPHARM","Pharma","Formulations"),
    ("CAPLIPOINT","Pharma","Formulations"),
    ("MARKSANS","Pharma","Formulations"),
    ("GRANULES","Pharma","Pharma API"),
    ("SHILPAMED","Pharma","Medical Devices"),
    ("KIMS","Pharma","Hospitals"),
    ("VIJAYADIAG","Pharma","Diagnostics"),
    ("METROPOLIS","Pharma","Diagnostics"),
    ("LALPATHLAB","Pharma","Diagnostics"),
    ("THYROCARE","Pharma","Diagnostics"),
    ("MEDANTA","Pharma","Hospitals"),
    ("RAINBOW","Pharma","Hospitals"),
    ("HEALTHCARE","Pharma","Hospitals"),
    ("MAXHEALTH","Pharma","Hospitals"),
    ("FORTIS","Pharma","Hospitals"),
    ("NHLIND","Pharma","Hospitals"),
    ("KRSNAA","Pharma","Diagnostics"),
    ("SEQUENT","Pharma","Pharma API"),
    ("SOLARA","Pharma","Pharma API"),
    ("YATHARTH","Pharma","Hospitals"),
    ("MEDPLUS","Pharma","Retail Pharma"),
    ("TGSOLS","Pharma","Diagnostics"),
    ("NEULANDLAB","Pharma","Pharma API"),
    ("NAUKRI","Internet","Job Portal"),

    # ── CHEMICALS & SPECIALTY ────────────────────────────────────────────────
    ("NOCIL","Chemicals","Rubber Chemicals"),
    ("AARTI","Chemicals","Specialty Chemicals"),
    ("VINATI","Chemicals","Specialty Chemicals"),
    ("NEOGEN","Chemicals","Specialty Chemicals"),
    ("FINEORG","Chemicals","Food & Oleo Chemicals"),
    ("DMCC","Chemicals","Specialty Chemicals"),
    ("TATACHEM","Chemicals","Commodity Chemicals"),
    ("GNFC","Chemicals","Agro Chemicals"),
    ("GUJALKALI","Chemicals","Chlor-Alkali"),
    ("DCWLTD","Chemicals","Chlor-Alkali"),
    ("AKZOINDIA","Chemicals","Paints & Coatings"),
    ("KANSAINER","Chemicals","Paints & Coatings"),
    ("INDIGO","Chemicals","Specialty Chemicals"),
    ("TRANSPEK","Chemicals","Specialty Chemicals"),
    ("GALAXYSURF","Chemicals","Surfactants"),
    ("GOKUL","Chemicals","Agro Chemicals"),
    ("HEMIPROP","Chemicals","Specialty Chemicals"),
    ("EPIGRAL","Chemicals","Specialty Chemicals"),
    ("DEEPAKNTR","Chemicals","Specialty Chemicals"),
    ("CLEAN","Chemicals","Specialty Chemicals"),
    ("ROSSARI","Chemicals","Specialty Chemicals"),
    ("NUVOCO","Infra","Cement"),
    ("HGINFRA","Infra","EPC"),
    ("CHEMCON","Chemicals","Pharma Chemicals"),
    ("JUBILANTIND","Chemicals","Specialty Chemicals"),
    ("ALKYL","Chemicals","Specialty Chemicals"),
    ("PAUSHAKLTD","Chemicals","Pharma Chemicals"),
    ("TCIEXP","Infra","Logistics"),
    ("GLAND","Pharma","Injectable Pharma"),

    # ── AUTO & AUTO COMPONENTS ───────────────────────────────────────────────
    ("OLECTRA","Auto","Electric Buses"),
    ("GREAVES","Auto","Auto Components"),
    ("CRAFTSMAN","Auto","Auto Components"),
    ("SUBROS","Auto","Auto Components"),
    ("SUPRAJIT","Auto","Auto Components"),
    ("GABRIEL","Auto","Auto Components"),
    ("FIEM","Auto","Auto Components"),
    ("JMTAUTOLTD","Auto","Auto Components"),
    ("KPIL","Auto","Auto Components"),
    ("SMLISUZU","Auto","Commercial Vehicles"),
    ("HINDMOTORS","Auto","Passenger Vehicles"),
    ("PREMIERPOL","Packaging","Polymer Packaging"),
    ("IGARASHI","Auto","Auto Components"),
    ("SWARAJENG","Auto","Tractors"),
    ("ESCORTS","Auto","Tractors & Agri Equipment"),
    ("VST","Auto","Tractors"),
    ("KERNEX","Auto","Auto Safety Systems"),
    ("LUMAXIND","Auto","Auto Lighting"),
    ("UCALFUEL","Auto","Fuel Systems"),
    ("RACL","Auto","Precision Components"),
    ("ENDURANCE","Auto","Auto Components"),
    ("RICO","Auto","Auto Die Casting"),
    ("KALYANKJIL","Consumer","Jewellery"),
    ("PNCINFRA","Infra","Roads & Highways"),
    ("SANDHAR","Auto","Auto Components"),
    ("SETCO","Auto","Clutches"),
    ("SPARC","Pharma","Drug Discovery"),
    ("JAMNAAUTO","Auto","Auto Components"),
    ("PRICOL","Auto","Auto Instruments"),

    # ── METALS & MINING ──────────────────────────────────────────────────────
    ("MOIL","Metals","Manganese Ore"),
    ("GMDC","Metals","Mining"),
    ("NMDC","Metals","Iron Ore"),
    ("NATIONALUM","Metals","Aluminium"),
    ("VEDL","Metals","Diversified Metals"),
    ("HINDZINC","Metals","Zinc"),
    ("HINDCOPPER","Metals","Copper"),
    ("STERLITE","Metals","Copper"),
    ("TINPLATE","Metals","Tinplate"),
    ("RAMASTEEL","Metals","Steel"),
    ("JTLINFRA","Metals","Steel Pipes"),
    ("TIRUPATI","Metals","Graphite"),
    ("HATHWAY","IT","Cable TV & Broadband"),
    ("RATHI","Metals","Steel"),
    ("VISAKAIND","Metals","Steel"),
    ("LLOYDSENT","Metals","Steel"),
    ("GPIL","Metals","Sponge Iron"),
    ("SHYAMSTEEL","Metals","Steel"),
    ("SUNFLAG","Metals","Steel"),
    ("ROHLTD","Metals","Iron & Steel"),
    ("STEELCAS","Metals","Steel"),
    ("MMTC","Metals","Metal Trading"),
    ("KIOCL","Metals","Iron Ore"),
    ("MSTCLTD","Metals","Metal Trading"),
    ("GRAVITA","Metals","Lead Recycling"),
    ("HINDPOW","Metals","Ferro Alloys"),
    ("MIDHANI","Metals","Aerospace Alloys"),
    ("MANGLAM","Metals","Steel Wires"),
    ("USHA","Metals","Steel Wires"),
    ("SHRIRAMPPS","Metals","Steel Wires"),

    # ── CAPITAL GOODS / ENGINEERING ─────────────────────────────────────────
    ("GEPIL","Cap Goods","Industrial Gases"),
    ("INOXAIR","Cap Goods","Industrial Gases"),
    ("APARINDS","Cables","Cables & Wires"),  # APAR Industries = conductors, cables, transformer oil; NOT Cap Goods
    ("VOLTAMP","Cap Goods","Transformers"),
    ("HITECHCORP","Cap Goods","Electrical Equipment"),
    ("TDPOWERSYS","Cap Goods","Alternators"),
    ("GRSE","Cap Goods","Shipbuilding"),
    ("MDL","Cap Goods","Shipbuilding"),
    ("COCHINSHIP","Cap Goods","Shipbuilding"),
    ("HSCL","Cap Goods","Heavy Structures"),
    ("SUZLON","Renewable","Wind Energy"),
    ("WINDWORLD","Renewable","Wind Energy"),
    ("REGEN","Renewable","Wind Energy"),
    ("PRECWIRE","Cap Goods","Wires & Cables"),
    ("FINOLEX","Cables","Cables"),
    ("KEI","Cables","Cables"),
    ("KECL","Cap Goods","Power Transmission"),
    ("KALPATPOWR","Cap Goods","EPC"),
    ("SKIPPER","Cap Goods","Power Towers"),
    ("JYOTISTRUC","Cap Goods","Power Towers"),
    ("APAR","Cap Goods","Conductors"),
    ("VIKAS","Cap Goods","Wires"),
    ("STERLITEIND","Cables","Cables"),
    ("VIMTALABS","Pharma","Testing Labs"),
    ("EQUINOX","IT","Data Centers"),
    ("NRAIL","Cap Goods","Rails"),
    ("TEXMOPIPES","Cap Goods","Pipes"),
    ("HCALPIPES","Cap Goods","Pipes"),
    ("SUNTECKINS","Cap Goods","Water Tech"),
    ("EASEMYTRIP","Internet","Online Travel"),

    # ── DEFENSE ──────────────────────────────────────────────────────────────
    ("ELCOMPONENT","Defense","Defense Electronics"),
    ("APOLLO","Defense","Defense"),
    ("PARAS","Defense","Defense"),
    ("ROSSELL","Defense","Defense Aerospace"),
    ("SANGHVIMOV","Infra","Cranes & Lifting"),
    ("MTAR","Defense","Aerospace & Defense"),
    ("ZODIAC","Defense","Aerospace Components"),
    ("AVAADA","Renewable","Solar Energy"),
    ("RATTANINDIA","Renewable","Renewable Energy"),
    ("WEBSOL","Renewable","Solar Cells"),
    ("WAAREEENER","Renewable","Solar Modules"),
    ("PREMIER","Renewable","Solar"),
    ("GANESHA","Textiles","Technical Textiles"),
    ("UFLEX","Packaging","Flexible Packaging"),
    ("NUCLEUS","IT","IT Products - Banking"),

    # ── INFRASTRUCTURE / EPC ─────────────────────────────────────────────────
    ("NBCC","Infra","PSU Construction"),
    ("RITES","Infra","Transport Consulting"),
    ("WABAG","Infra","Water Treatment"),
    ("VA","Infra","EPC"),
    ("SPML","Infra","Water EPC"),
    ("ION","IT","E-Governance"),
    ("SIEVERT","Infra","Water Treatment"),
    ("INDIAGRID","Infra","Power Transmission"),
    ("TORNTPIPER","Infra","Gas Pipelines"),
    ("IGL","Energy","City Gas Distribution"),
    ("MGL","Energy","City Gas Distribution"),
    ("GSPL","Energy","Gas Pipeline"),
    ("GUJGAS","Energy","City Gas Distribution"),
    ("AEGASIND","Energy","City Gas Distribution"),
    ("MAHGL","Energy","City Gas Distribution"),
    ("SABTN","Energy","City Gas Distribution"),
    ("APOLLOPIPE","Infra","CPVC/PVC Pipes"),
    ("PRINCEPIPE","Infra","CPVC/PVC Pipes"),
    ("FINOLEX","Infra","CPVC/PVC Pipes"),
    ("ASHIRVAD","Infra","Plastic Pipes"),
    ("HISARMET","Metals","Steel"),

    # ── CONSUMER / FMCG ──────────────────────────────────────────────────────
    ("BALAMINES","Consumer","Food Products"),
    ("HERITGFOOD","Consumer","Dairy"),
    ("PARAG","Consumer","Dairy"),
    ("DODLA","Consumer","Dairy"),
    ("PRABHAT","Consumer","Dairy"),
    ("ABIRLANUVO","Consumer","Diversified Consumer"),
    ("EMAMILTD","Consumer","FMCG"),
    ("BAJAJCONS","Consumer","FMCG"),
    ("VBLLTD","Consumer","Beverages"),
    ("RADICO","Consumer","Spirits"),
    ("GLOBUSSPR","Consumer","Spirits"),
    ("TILIND","Consumer","Spirits"),
    ("SULAVIN","Consumer","Wine"),
    ("DRREDDY","Pharma","Formulations"),
    ("WHIRLPOOL","Consumer","White Goods"),
    ("VOLTAS","Consumer","Air Conditioning"),
    ("CROMPTON","Consumer","Consumer Electricals"),
    ("ORIENTELEC","Consumer","Consumer Electricals"),
    ("USHA","Consumer","Consumer Electricals"),
    ("BAJAJELEC","Consumer","Consumer Electricals"),
    ("SYRMA","Electronics","Electronic Manufacturing"),
    ("VGUARD","Consumer","Consumer Electricals"),
    ("CERA","Consumer","Sanitaryware"),
    ("HINDWARE","Consumer","Sanitaryware"),
    ("HSIL","Consumer","Sanitaryware"),
    ("KAJARIACER","Consumer","Tiles"),
    ("ASIANTILES","Consumer","Tiles"),
    ("SOMANY","Consumer","Tiles"),
    ("ORIENTBELL","Consumer","Tiles"),
    ("NITISHK","Consumer","Tiles"),
    ("GREENPANEL","Consumer","Wood Panels"),
    ("CENTURYPLY","Consumer","Plywood"),
    ("STYLAMIND","Consumer","Laminates"),
    ("MRPL","Energy","Refineries"),
    ("BOROSIL","Consumer","Glassware"),
    ("HLEGLAS","Consumer","Glassware"),

    # ── REAL ESTATE / REITs ──────────────────────────────────────────────────
    ("MAHINDCIE","Auto","Auto Components - Forgings"),
    ("NESCO","RealEstate","Commercial RE"),
    ("BRIGADE","RealEstate","Residential RE"),
    ("PRESTIGE","RealEstate","Residential RE"),
    ("PURAVANK","RealEstate","Residential RE"),
    ("MAHLIFE","RealEstate","Residential RE"),
    ("KOLTEPATIL","RealEstate","Residential RE"),
    ("ARVIND","Textiles","Textiles - Apparel"),  # Arvind Limited = textile conglomerate; Arvind SmartSpaces (ARVSMART) is the RE arm, NOT ARVIND itself
    ("CENTURYTEX","Textiles","Textiles - Apparel"),  # Century Textiles & Industries = textiles/building products; NOT Real Estate (Birla Estates is subsidiary)
    ("SUNTECK","RealEstate","Residential RE"),
    ("ARVSMART","RealEstate","Residential RE"),
    ("GODREJPROP","RealEstate","Residential RE"),
    ("SOBHA","RealEstate","Residential RE"),
    ("EMBASSY","RealEstate","REIT"),
    ("MINDSPACE","RealEstate","REIT"),
    ("NEXUS","RealEstate","REIT"),
    ("JSWREALTY","RealEstate","Residential RE"),
    ("EXPERION","RealEstate","Residential RE"),

    # ── TEXTILES / APPAREL ────────────────────────────────────────────────────
    ("NYKAA","Internet","Beauty E-Commerce"),
    ("VEDANT","Consumer","Fashion Retail"),
    ("MANYAVAR","Consumer","Fashion Retail"),
    ("METRO","Consumer","Footwear"),
    ("CAMPUS","Consumer","Footwear"),
    ("BATA","Consumer","Footwear"),
    ("RELAXO","Consumer","Footwear"),
    ("LEHAR","Consumer","Footwear"),
    ("LIBERTY","Consumer","Footwear"),
    ("KHADIM","Consumer","Footwear"),
    ("AADINATH","Textiles","Textile Processing"),
    ("NIKHILAD","Textiles","Technical Textiles"),
    ("NMSWORKS","Textiles","Textiles"),
    ("TAICHI","Textiles","Technical Textiles"),
    ("RSWM","Textiles","Textiles - Spinning"),
    ("OWM","Textiles","Woolen Mills"),
    ("BOMBDYING","Textiles","Textiles - Processing"),
    ("ANUP","Cap Goods","Engineering"),  # ANUP Engineering = pressure vessels & heat exchangers for petrochemicals; NOT Textiles
    ("SUTLEJ","Textiles","Textiles - Spinning"),
    ("DPABHUSHAN","Consumer","Jewellery"),
    ("GOLDIAM","Consumer","Jewellery"),
    ("TARA","Consumer","Jewellery"),
    ("VAIBHAVGBL","Consumer","Jewellery"),
    ("SENCO","Consumer","Jewellery"),
    ("PCJEWELLER","Consumer","Jewellery"),
    ("THANGAMAYL","Consumer","Jewellery"),
    ("JOJALGOLD","Consumer","Jewellery"),

    # ── AGRI / FOOD PROCESSING ───────────────────────────────────────────────
    ("KRBL","Agri","Rice"),
    ("LTFOODS","Agri","Rice"),
    ("CHAMAN","Agri","Rice"),
    ("SUPRAGRI","Agri","Agri Products"),
    ("ASTERDM","Pharma","Hospitals"),
    ("JKPAPER","Consumer","Paper"),
    ("TNPL","Consumer","Paper"),
    ("WESPAPER","Consumer","Paper"),
    ("NATHPULP","Consumer","Paper & Pulp"),
    ("KUANTUMGLO","Consumer","Packaging"),
    ("SATIA","Consumer","Paper"),
    ("STARPAPL","Consumer","Paper"),
    ("ANDHRAPER","Consumer","Paper"),
    ("SHREYANS","Consumer","Paper"),
    ("EMAMI","Consumer","FMCG"),
    ("MARICO","Consumer","FMCG"),
    ("HATSUN","Consumer","Dairy"),
    ("KWALITY","Consumer","Dairy"),
    ("TASTY","Consumer","Food Products"),
    ("VADILALIND","Consumer","Ice Cream"),
    ("CREMICAP","Consumer","Ice Cream"),
    ("CREAMBELL","Consumer","Ice Cream"),
    ("SUNPHARMA","Pharma","Formulations"),
    ("ANURAS","Agri","Seeds"),
    ("SHRIRAMFRT","Agri","Fertilisers"),
    ("FACT","Agri","Fertilisers"),
    ("IFFCO","Agri","Fertilisers"),
    ("NFL","Agri","Fertilisers"),
    ("GNFC","Agri","Fertilisers"),
    ("CHAMBAL","Agri","Fertilisers"),
    ("COROMANDEL","Agri","Fertilisers & Agro Chem"),
    ("PI","Agri","Agro Chemicals"),
    ("DHANUKA","Agri","Agro Chemicals"),
    ("RALLIS","Agri","Agro Chemicals"),
    ("INSECTICID","Agri","Agro Chemicals"),
    ("BIOCON","Pharma","Biologics"),
    ("WOCKHARDT","Pharma","Formulations"),
    ("HESTER","Pharma","Veterinary"),
    ("VETOQUINOL","Pharma","Veterinary"),
    ("VIPPY","Agri","Agri Processing"),
    ("KOTHARIPRO","Agri","Agri Processing"),
    ("AVANTIFEED","Agri","Shrimp Feed"),
    ("WATERBASE","Agri","Shrimp Feed"),
    ("APEX","Agri","Shrimp Feed"),

    # ── SHIPPING / PORTS / LOGISTICS ─────────────────────────────────────────
    ("SCI","Shipping","Shipping"),
    ("ESCORIT","Shipping","Shipping"),
    ("SEAMECLTD","Shipping","Ship Repair"),
    ("SHREYAS","Shipping","Container Logistics"),
    ("MAHESHWARI","Shipping","Shipping"),
    ("ESAB","Cap Goods","Welding Equipment"),
    ("CMSINFO","IT","Cash Management"),
    ("PROSTARM","Cap Goods","UPS & Power"),
    ("AMARA","Auto","Batteries"),
    ("EXIDEIND","Auto","Batteries"),
    ("HBLPOWER","Auto","Batteries"),
    ("RAMAKRISHNA","Metals","Copper Products"),
    ("TATACOMM","IT","Telecom"),
    ("RAILTEL","IT","Telecom - Rail"),
    ("BSNL","IT","Telecom"),
    ("GTLINFRA","IT","Telecom Towers"),
    ("BIRLATELE","IT","Telecom"),
    ("STLTECH","Cables","Optical Fibre"),
    ("HFCL","Cables","Optical Fibre"),
    ("VINDHYATEL","Cables","Optical Fibre"),
    ("ASIANENE","Cables","Cables"),
    ("PARAMOUNT","Cables","Cables"),
    ("HAVELLS","Consumer","Consumer Electricals"),
    ("POLYCAB","Cables","Cables"),
    ("RRKABEL","Cables","Cables"),
    ("SKYGOLD","Consumer","Jewellery"),
    ("SAPPHIRE","Textiles","Textiles"),
    ("WELCABLE","Cables","Cables"),

    # ── RETAIL / QUICK COMMERCE ──────────────────────────────────────────────
    ("DMART","Consumer","Retail"),
    ("VMART","Consumer","Retail"),
    ("SHOPSTOP","Consumer","Retail"),
    ("TRENT","Consumer","Retail - Fashion"),
    ("SPENCERS","Consumer","Retail"),
    ("JUBLFOOD","Consumer","QSR"),
    ("DEVYANI","Consumer","QSR"),
    ("WESTLIFE","Consumer","QSR"),
    ("SAPPHIREF","Consumer","QSR"),
    ("BARBEQUE","Consumer","Restaurants"),
    ("IRCTC","Internet","Online Travel"),
    ("MAHINDHOLIDAY","Consumer","Travel & Tourism"),
    ("INDHOTELS","Consumer","Hotels"),
    ("EIHOTEL","Consumer","Hotels"),
    ("LEEHOLIDAY","Consumer","Hotels"),
    ("CHALET","Consumer","Hotels"),
    ("TAJGVK","Consumer","Hotels"),
    ("ITCHOTELS","Consumer","Hotels"),
    ("LEMONTRE","Consumer","Hotels"),
    ("SAMHI","Consumer","Hotels"),
    ("VENTIVE","Consumer","Hospitality"),
    ("GMRINFRA","Infra","Airports"),
    ("ADANIAIRPORT","Infra","Airports"),
    ("INTERGLOBE","Consumer","Aviation"),
    ("SPICEJET","Consumer","Aviation"),
    ("AKASAAIR","Consumer","Aviation"),

    # ── MEDIA / ENTERTAINMENT ────────────────────────────────────────────────
    ("SAREGAMA","Consumer","Music & Content"),
    ("TIPS","Consumer","Music"),
    ("EROS","Consumer","Media & Entertainment"),
    ("EROSMEDIA","Consumer","Media & Entertainment"),
    ("PVRINOX","Consumer","Multiplex"),
    ("INOX","Consumer","Multiplex"),
    ("NAZARA","Internet","Gaming"),
    ("DELTACORP","Consumer","Gaming & Casinos"),
    ("HATHWAY","IT","Cable TV"),
    ("SUNTV","Consumer","TV Broadcasting"),
    ("ZEEL","Consumer","TV Broadcasting"),
    ("NETWORK18","Consumer","TV Broadcasting"),
    ("NDTV","Consumer","TV Broadcasting"),
    ("TV18BRDCST","Consumer","TV Broadcasting"),
    ("DISHTV","Consumer","DTH"),
    ("TATASKY","Consumer","DTH"),
    ("BEML","Cap Goods","Heavy Engineering - Defense"),
    ("MAZDOCK","Cap Goods","Shipbuilding"),
    ("GOA","Cap Goods","Shipbuilding"),

    # ── RENEWABLE / GREEN ENERGY ─────────────────────────────────────────────
    ("TORNTPOWER","Energy","Power"),
    ("CESC","Energy","Power"),
    ("JPPOWER","Energy","Power"),
    ("RPOWER","Energy","Power"),
    ("GIPCL","Energy","Power"),
    ("ADANIGREEN","Renewable","Solar Energy"),
    ("GREENKO","Renewable","Renewable Energy"),
    ("ACMESOLAR","Renewable","Solar Energy"),
    ("INDIGRID","Infra","Power Transmission InvIT"),
    ("POWERMECH","Cap Goods","Power Plant EPC"),
    ("KALINDEE","Cap Goods","Rail Electrification"),
    ("KIRIIND","Renewable","Green Hydrogen"),
    ("ATGL","Energy","City Gas Distribution"),
    ("GUJRATGAS","Energy","City Gas Distribution"),
    ("HYUNDAI","Auto","Passenger Vehicles"),
    ("OLA","Auto","Electric Vehicles"),
    ("TATAMOTOR","Auto","Diversified Vehicles"),

    # ── ELECTRONICS / EMS ────────────────────────────────────────────────────
    ("AMBER","Electronics","Electronic Manufacturing"),
    ("DIXON","Electronics","Electronic Manufacturing"),
    ("KAYNES","Electronics","Electronic Manufacturing"),
    ("PGEL","Electronics","Electronic Manufacturing"),
    ("SAHASRA","Electronics","Electronic Manufacturing"),
    ("RAJESHEXPO","Electronics","Silver & Gold Refining"),
    ("CENTUM","Electronics","Defense Electronics"),
    ("BHEL","Cap Goods","Heavy Engineering"),
    ("MFSL","Financials","Insurance"),
    ("ELGIEQUIP","Cap Goods","Compressors"),
    ("SANGHVI","Cap Goods","Cranes"),
    ("TEXINFRA","Infra","Infrastructure"),
    ("LIKHITHA","Infra","Pipeline EPC"),
    ("CREST","Cap Goods","Pumps"),
    ("ROTO","Cap Goods","Pumps"),
    ("KIRLOSBROS","Cap Goods","Pumps"),
    ("MESCAB","Cables","Cables"),

    # ── POWER SECTOR ─────────────────────────────────────────────────────────
    ("POWERGRIDINVIT","Infra","Power InvIT"),
    ("PFCINDIA","Financials","Power Finance"),
    ("RECLTD","Financials","Power Finance"),
    ("IRFC","Financials","Railway Finance"),
    ("NPCIL","Energy","Nuclear Power"),
    ("MOSDOH","Energy","Renewable"),
    ("NESCO","Cap Goods","Exhibition Centers"),

    # ── MISCELLANEOUS / HOLDING ──────────────────────────────────────────────
    ("KALYANI","Auto","Diversified - Kalyani Group"),
    ("BALAJIAM","Consumer","Snacks"),
    ("PRATAAP","Consumer","Snacks"),
    ("DFM","Consumer","Food Products"),
    ("BIKAJI","Consumer","Snacks"),
    ("ITC","Consumer","Diversified FMCG"),
    ("GODFREY","Consumer","Tobacco"),
    ("VST","Consumer","Tobacco"),
    ("4THAND","Consumer","Tobacco"),
    ("GILLETTE","Consumer","Personal Care"),
    ("COLPAL","Consumer","Personal Care"),
    ("PGHH","Consumer","Personal Care"),
    ("JYOTHY","Consumer","Personal Care"),
    ("THEJEWELS","Consumer","Jewellery"),
    ("SOMANYCERA","Consumer","Tiles"),
    ("CGPOWER","Cap Goods","Power Equipment"),
    ("SIEMENS","Cap Goods","Diversified Engineering"),
    ("ABB","Cap Goods","Diversified Engineering"),
    ("HONAUT","Cap Goods","Automation"),
    ("3MINDIA","Cap Goods","Specialty Materials"),
    ("MOLD","Cap Goods","Moldtek"),
    ("MOLDTKPAC","Packaging","Rigid Packaging"),
    ("HUHTAMAKI","Packaging","Flexible Packaging"),
    ("MIRCELECTR","Consumer","Electronics"),
    ("ONMOBILE","IT","Telecom VAS"),
    ("RATEGAIN","IT","Travel Technology SaaS"),
    ("INDIACEM","Infra","Cement"),
    ("JKCEMENT","Infra","Cement"),
    ("RAMCOCEM","Infra","Cement"),
    ("HEIDELBERG","Infra","Cement"),
    ("BIRLACORP","Infra","Cement"),
    ("SHREECEM","Infra","Cement"),
    ("AMBUJACEM","Infra","Cement"),
    ("ACCIND","Infra","Cement"),
    ("DALMIACEM","Infra","Cement"),
    ("JSWCEM","Infra","Cement"),
    ("SANGHI","Infra","Cement"),
    ("SAURASHTRA","Infra","Cement"),
    ("KAKATCEM","Infra","Cement"),
    ("BURNPUR","Metals","Sponge Iron"),
    ("LLOYDS","Consumer","Air Conditioning"),
    ("BLUE","Consumer","Air Conditioning"),
    ("GODREJAP","Consumer","Home Appliances"),
    ("PHILIPSBV","Consumer","Healthcare Equipment"),
    ("PATANJALI","Consumer","FMCG"),
    ("DABUR","Consumer","FMCG - Ayurveda"),
    ("HIMALAYA","Consumer","FMCG - Ayurveda"),
    ("EMCURE","Pharma","Formulations"),
    ("ALKEM","Pharma","Formulations"),
    ("TORNTPHARM","Pharma","Formulations"),
    ("AJANTPHARM","Pharma","Formulations"),
    ("ERIS","Pharma","Formulations"),
    ("JB","Pharma","Formulations"),
    ("INDOCO","Pharma","Formulations"),
    ("SYMPHONY","Consumer","Air Coolers"),
    ("HAWKINS","Consumer","Pressure Cookers"),
    ("TTK","Consumer","Pressure Cookers"),
    ("WONDERLA","Consumer","Amusement Parks"),
    ("BARBEQUE","Consumer","Restaurants"),
    ("SPECIALITY","Consumer","Restaurants"),
    ("WESTLIFE","Consumer","QSR - McDonald's"),
    ("JUBILANT","Consumer","Diversified Consumer"),
    ("JUBLPHARMA","Pharma","Pharma API - CDMO"),
    ("GLENMARK","Pharma","Formulations"),
    ("NATCO","Pharma","Formulations"),
    ("ACCELYA","IT","Airline IT"),
    ("QUICKHEAL","IT","Cybersecurity"),
    ("TATATECH","IT","Engineering Services"),
    ("NEWGEN","IT","BPM Software"),
    ("TANLA","IT","Cloud Communications"),
    ("SUVENPHAR","Pharma","Drug Discovery - CDMO"),
    ("AGANORA","Pharma","Formulations"),
    ("ENTERO","Pharma","Pharma Distribution"),
    ("MEDKART","Pharma","Generic Pharma Retail"),
    ("CAMS","Financials","Financial Services - RTA"),
    ("CDSL","Financials","Depositories"),
    ("BSE","Financials","Stock Exchanges"),
    ("MCXINDIA","Financials","Commodities Exchange"),
    ("LOTUSEYE","Pharma","Eye Hospitals"),
    ("VISIONCARE","Pharma","Eye Hospitals"),
    ("ASK","Financials","Wealth Management"),
    ("360ONE","Financials","Wealth Management"),
    ("ANAND","Auto","Auto Components"),
    ("FOSECOIND","Metals","Foundry Chemicals"),
    ("HINDPETRO","Energy","Refineries"),
    ("BPCL","Energy","Refineries"),
    ("IOC","Energy","Refineries"),
    ("ONGC","Energy","Oil Exploration"),
    ("CAIRN","Energy","Oil Exploration"),
    ("OILINDIA","Energy","Oil Exploration"),
    ("PETRONET","Energy","LNG"),
    ("GSPL","Energy","Gas Pipeline"),
    ("JSWESL","Energy","Power"),
    ("TATASTEEL","Metals","Steel"),
    ("JSWSTEEL","Metals","Steel"),
    ("SAIL","Metals","Steel - PSU"),
    ("HINDALCO","Metals","Aluminium"),
    ("ALUCAST","Metals","Aluminium Die Casting"),
    ("RATNA","Metals","Steel"),
    ("VEDANTA","Metals","Diversified Metals"),
    ("COALINDIA","Energy","Coal Mining - PSU"),
    ("CSTLTD","Metals","Steel"),
    ("RTNL","Metals","Steel"),
    ("PSPPROJECT","Infra","EPC"),
    ("SAPPHIREFOO","Consumer","Food Products"),
    ("ANANTRAJ","RealEstate","Commercial RE"),
    ("SUNTECKREAL","RealEstate","Residential RE"),
    ("MACROTECH","RealEstate","Residential RE - Lodha"),
    ("DLF","RealEstate","Residential RE"),
    ("OBEROIREAL","RealEstate","Residential RE"),
    ("INDIABULLS","RealEstate","Residential RE"),
    ("PHOENIXLTD","RealEstate","Retail RE"),
    ("IBREALEST","RealEstate","Commercial RE"),
    ("OMAXE","RealEstate","Residential RE"),
    ("TATAHOUSING","RealEstate","Residential RE"),
    ("AARTISURF","Chemicals","Surfactants"),
    ("ALLCARGO","Infra","Logistics"),
    ("GATI","Infra","Logistics"),
    ("DTIL","Infra","Logistics"),
    ("MAHLOG","Infra","Logistics"),
    ("SNOWMAN","Infra","Cold Chain Logistics"),
    ("CONCOR","Infra","Rail Logistics"),
    ("DELHIVERY","Infra","Logistics"),
    ("XPRESSBEES","Infra","Logistics"),
    ("BLUEDART","Infra","Express Logistics"),
    ("DTDC","Infra","Logistics"),
    ("EKART","Infra","Logistics"),
    ("TLGLOBAL","Infra","Logistics"),
    ("WOCKHARDT","Pharma","Formulations"),
]

added2 = 0
upgraded2 = 0
for entry in BATCH2:
    t, sector, industry = entry[0].upper().strip(), entry[1], entry[2]
    if t not in existing:
        existing[t] = {"nse_ticker": t, "sector": sector, "industry": industry, "notes": ""}
        added2 += 1
    elif existing[t].get("sector","") in ("","Other") or existing[t].get("industry","") in ("","Other"):
        existing[t]["sector"] = sector
        existing[t]["industry"] = industry
        upgraded2 += 1

# Re-sort and write
sorted_rows2 = sorted(existing.values(), key=lambda r: r.get("nse_ticker","").upper())
with open(CSV, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    writer.writerows(sorted_rows2)

print(f"\nBatch 2 — Added: {added2}  Upgraded: {upgraded2}  Final total: {len(sorted_rows2)}")
from collections import Counter as _C2
by_sector2 = _C2(r.get("sector","") for r in sorted_rows2)
print("\nFinal sector distribution:")
for sec, cnt in by_sector2.most_common(25):
    print(f"  {sec:30s} {cnt:4d}")
by_industry = _C2(r.get("industry","") for r in sorted_rows2)
print(f"\nTotal unique industries: {len(by_industry)}")

